package com.munchicken.multidonutsmod.handlers;

import com.munchicken.multidonutsmod.items.ItemDonuts;
import com.munchicken.multidonutsmod.items.ModItems;
import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.block.Block;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;

public class ModRecipes {

    public static void addRecipes(){

        GameRegistry.addRecipe(new ItemStack(ModItems.dough), new Object[] {
                " W ",
                "X Z",
                " Y ",
                'W', Items.milk_bucket, 'X', Items.sugar, 'Y', Items.wheat, 'Z', Items.egg
        });

        GameRegistry.addRecipe(new ItemStack(ModItems.rollingPin), new Object[]{
                "   ",
                "XYX",
                "   ",
                'X', Items.stick, 'Y', Blocks.planks
        });

        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.flatDough), new Object[]{
                ModItems.dough, ModItems.rollingPin
        });

        GameRegistry.addRecipe(new ItemStack(ModItems.cutter), new Object[]{
                " X ",
                "X X",
                " X ",
                'X', Items.iron_ingot
        });

        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.rawDonut), new Object[]{
                ModItems.flatDough, ModItems.cutter
        });

        GameRegistry.addSmelting(new ItemStack(ModItems.rawDonut), new ItemStack(ModItems.cookedDonut), 0.1F);

        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.pastryBag), new Object[]{
                Blocks.chest, Blocks.hopper
        });

        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.shaker), new Object[]{
                Blocks.iron_bars, Items.bucket
        });

        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.strawberryIcing), new Object[]{
                Items.sugar, ModItems.strawberry
        });

        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.chocolateIcing), new Object[]{
                Items.sugar, new ItemStack(Items.dye,1,3)
        });

        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.blueberryIcing), new Object[]{
                Items.sugar, ModItems.blueberry
        });

        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.vanillaIcing), new Object[]{
                Items.sugar, ModItems.vanillaBean
        });

        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.greenSprinkles), new Object[]{
                Items.sugar, new ItemStack(Items.dye,1,2)
        });

        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.blueSprinkles), new Object[]{
                Items.sugar, new ItemStack(Items.dye,1,4)
        });

        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.redSprinkles), new Object[]{
                Items.sugar, new ItemStack(Items.dye,1,1)
        });

        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.yellowSprinkles), new Object[]{
                Items.sugar, new ItemStack(Items.dye,1,11)
        });

        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.orangeSprinkles), new Object[]{
                Items.sugar, new ItemStack(Items.dye,1,14)
        });

        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.rainbowSprinkles), new Object[]{
                Items.sugar, new ItemStack(Items.dye,1,14), new ItemStack(Items.dye,1,11), new ItemStack(Items.dye,1,1), new ItemStack(Items.dye,1,4), new ItemStack(Items.dye,1,2)
        });

        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.strawberryFilling), new Object[]{
                Items.sugar, Items.water_bucket, ModItems.strawberry
        });

        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.chocolateFilling), new Object[]{
                Items.sugar, Items.water_bucket, new ItemStack(Items.dye,1,3)
        });

        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.vanillaFilling), new Object[]{
                Items.sugar, Items.water_bucket, ModItems.vanillaBean
        });

        GameRegistry.addRecipe(new ItemStack(ModItems.cookieDoughFilling), new Object[]{
                " W ",
                "XYX",
                " Z ",
                'W', Items.water_bucket, 'X', Items.wheat, 'Y', new ItemStack(Items.dye, 1, 3), 'Z', Items.sugar
        });

        GameRegistry.addRecipe(new ItemStack(ModItems.brownieBatterFilling), new Object[]{
                " W ",
                "XYX",
                " Z ",
                'W', Items.water_bucket, 'X', new ItemStack(Items.dye,1,3), 'Y', Items.wheat, 'Z', Items.sugar
        });

        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.fillingTube), new Object[]{
                Items.bucket, Blocks.hopper
        });

        /*
        * begin - Auto generated by DonutCombos.py
        */
        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.noneNoneStrawberryDonut), new Object[]{
                ModItems.cookedDonut, ModItems.strawberryFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.noneNoneChocolateDonut), new Object[]{
                ModItems.cookedDonut, ModItems.chocolateFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.noneNoneVanillaDonut), new Object[]{
                ModItems.cookedDonut, ModItems.vanillaFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.noneNoneCookieDoughDonut), new Object[]{
                ModItems.cookedDonut, ModItems.cookieDoughFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.noneNoneBrownieBatterDonut), new Object[]{
                ModItems.cookedDonut, ModItems.brownieBatterFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.noneGreenNoneDonut), new Object[]{
                ModItems.cookedDonut, ModItems.greenSprinkles, ModItems.shaker
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.noneGreenStrawberryDonut), new Object[]{
                ModItems.cookedDonut, ModItems.greenSprinkles, ModItems.shaker, ModItems.strawberryFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.noneGreenChocolateDonut), new Object[]{
                ModItems.cookedDonut, ModItems.greenSprinkles, ModItems.shaker, ModItems.chocolateFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.noneGreenVanillaDonut), new Object[]{
                ModItems.cookedDonut, ModItems.greenSprinkles, ModItems.shaker, ModItems.vanillaFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.noneGreenCookieDoughDonut), new Object[]{
                ModItems.cookedDonut, ModItems.greenSprinkles, ModItems.shaker, ModItems.cookieDoughFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.noneGreenBrownieBatterDonut), new Object[]{
                ModItems.cookedDonut, ModItems.greenSprinkles, ModItems.shaker, ModItems.brownieBatterFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.noneBlueNoneDonut), new Object[]{
                ModItems.cookedDonut, ModItems.blueSprinkles, ModItems.shaker
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.noneBlueStrawberryDonut), new Object[]{
                ModItems.cookedDonut, ModItems.blueSprinkles, ModItems.shaker, ModItems.strawberryFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.noneBlueChocolateDonut), new Object[]{
                ModItems.cookedDonut, ModItems.blueSprinkles, ModItems.shaker, ModItems.chocolateFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.noneBlueVanillaDonut), new Object[]{
                ModItems.cookedDonut, ModItems.blueSprinkles, ModItems.shaker, ModItems.vanillaFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.noneBlueCookieDoughDonut), new Object[]{
                ModItems.cookedDonut, ModItems.blueSprinkles, ModItems.shaker, ModItems.cookieDoughFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.noneBlueBrownieBatterDonut), new Object[]{
                ModItems.cookedDonut, ModItems.blueSprinkles, ModItems.shaker, ModItems.brownieBatterFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.noneRedNoneDonut), new Object[]{
                ModItems.cookedDonut, ModItems.redSprinkles, ModItems.shaker
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.noneRedStrawberryDonut), new Object[]{
                ModItems.cookedDonut, ModItems.redSprinkles, ModItems.shaker, ModItems.strawberryFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.noneRedChocolateDonut), new Object[]{
                ModItems.cookedDonut, ModItems.redSprinkles, ModItems.shaker, ModItems.chocolateFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.noneRedVanillaDonut), new Object[]{
                ModItems.cookedDonut, ModItems.redSprinkles, ModItems.shaker, ModItems.vanillaFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.noneRedCookieDoughDonut), new Object[]{
                ModItems.cookedDonut, ModItems.redSprinkles, ModItems.shaker, ModItems.cookieDoughFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.noneRedBrownieBatterDonut), new Object[]{
                ModItems.cookedDonut, ModItems.redSprinkles, ModItems.shaker, ModItems.brownieBatterFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.noneYellowNoneDonut), new Object[]{
                ModItems.cookedDonut, ModItems.yellowSprinkles, ModItems.shaker
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.noneYellowStrawberryDonut), new Object[]{
                ModItems.cookedDonut, ModItems.yellowSprinkles, ModItems.shaker, ModItems.strawberryFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.noneYellowChocolateDonut), new Object[]{
                ModItems.cookedDonut, ModItems.yellowSprinkles, ModItems.shaker, ModItems.chocolateFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.noneYellowVanillaDonut), new Object[]{
                ModItems.cookedDonut, ModItems.yellowSprinkles, ModItems.shaker, ModItems.vanillaFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.noneYellowCookieDoughDonut), new Object[]{
                ModItems.cookedDonut, ModItems.yellowSprinkles, ModItems.shaker, ModItems.cookieDoughFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.noneYellowBrownieBatterDonut), new Object[]{
                ModItems.cookedDonut, ModItems.yellowSprinkles, ModItems.shaker, ModItems.brownieBatterFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.noneOrangeNoneDonut), new Object[]{
                ModItems.cookedDonut, ModItems.orangeSprinkles, ModItems.shaker
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.noneOrangeStrawberryDonut), new Object[]{
                ModItems.cookedDonut, ModItems.orangeSprinkles, ModItems.shaker, ModItems.strawberryFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.noneOrangeChocolateDonut), new Object[]{
                ModItems.cookedDonut, ModItems.orangeSprinkles, ModItems.shaker, ModItems.chocolateFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.noneOrangeVanillaDonut), new Object[]{
                ModItems.cookedDonut, ModItems.orangeSprinkles, ModItems.shaker, ModItems.vanillaFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.noneOrangeCookieDoughDonut), new Object[]{
                ModItems.cookedDonut, ModItems.orangeSprinkles, ModItems.shaker, ModItems.cookieDoughFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.noneOrangeBrownieBatterDonut), new Object[]{
                ModItems.cookedDonut, ModItems.orangeSprinkles, ModItems.shaker, ModItems.brownieBatterFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.noneRainbowNoneDonut), new Object[]{
                ModItems.cookedDonut, ModItems.rainbowSprinkles, ModItems.shaker
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.noneRainbowStrawberryDonut), new Object[]{
                ModItems.cookedDonut, ModItems.rainbowSprinkles, ModItems.shaker, ModItems.strawberryFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.noneRainbowChocolateDonut), new Object[]{
                ModItems.cookedDonut, ModItems.rainbowSprinkles, ModItems.shaker, ModItems.chocolateFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.noneRainbowVanillaDonut), new Object[]{
                ModItems.cookedDonut, ModItems.rainbowSprinkles, ModItems.shaker, ModItems.vanillaFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.noneRainbowCookieDoughDonut), new Object[]{
                ModItems.cookedDonut, ModItems.rainbowSprinkles, ModItems.shaker, ModItems.cookieDoughFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.noneRainbowBrownieBatterDonut), new Object[]{
                ModItems.cookedDonut, ModItems.rainbowSprinkles, ModItems.shaker, ModItems.brownieBatterFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.strawberryNoneNoneDonut), new Object[]{
                ModItems.cookedDonut, ModItems.strawberryIcing, ModItems.pastryBag
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.strawberryNoneStrawberryDonut), new Object[]{
                ModItems.cookedDonut, ModItems.strawberryIcing, ModItems.pastryBag, ModItems.strawberryFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.strawberryNoneChocolateDonut), new Object[]{
                ModItems.cookedDonut, ModItems.strawberryIcing, ModItems.pastryBag, ModItems.chocolateFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.strawberryNoneVanillaDonut), new Object[]{
                ModItems.cookedDonut, ModItems.strawberryIcing, ModItems.pastryBag, ModItems.vanillaFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.strawberryNoneCookieDoughDonut), new Object[]{
                ModItems.cookedDonut, ModItems.strawberryIcing, ModItems.pastryBag, ModItems.cookieDoughFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.strawberryNoneBrownieBatterDonut), new Object[]{
                ModItems.cookedDonut, ModItems.strawberryIcing, ModItems.pastryBag, ModItems.brownieBatterFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.strawberryGreenNoneDonut), new Object[]{
                ModItems.cookedDonut, ModItems.strawberryIcing, ModItems.pastryBag, ModItems.greenSprinkles, ModItems.shaker
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.strawberryGreenStrawberryDonut), new Object[]{
                ModItems.cookedDonut, ModItems.strawberryIcing, ModItems.pastryBag, ModItems.greenSprinkles, ModItems.shaker, ModItems.strawberryFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.strawberryGreenChocolateDonut), new Object[]{
                ModItems.cookedDonut, ModItems.strawberryIcing, ModItems.pastryBag, ModItems.greenSprinkles, ModItems.shaker, ModItems.chocolateFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.strawberryGreenVanillaDonut), new Object[]{
                ModItems.cookedDonut, ModItems.strawberryIcing, ModItems.pastryBag, ModItems.greenSprinkles, ModItems.shaker, ModItems.vanillaFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.strawberryGreenCookieDoughDonut), new Object[]{
                ModItems.cookedDonut, ModItems.strawberryIcing, ModItems.pastryBag, ModItems.greenSprinkles, ModItems.shaker, ModItems.cookieDoughFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.strawberryGreenBrownieBatterDonut), new Object[]{
                ModItems.cookedDonut, ModItems.strawberryIcing, ModItems.pastryBag, ModItems.greenSprinkles, ModItems.shaker, ModItems.brownieBatterFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.strawberryBlueNoneDonut), new Object[]{
                ModItems.cookedDonut, ModItems.strawberryIcing, ModItems.pastryBag, ModItems.blueSprinkles, ModItems.shaker
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.strawberryBlueStrawberryDonut), new Object[]{
                ModItems.cookedDonut, ModItems.strawberryIcing, ModItems.pastryBag, ModItems.blueSprinkles, ModItems.shaker, ModItems.strawberryFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.strawberryBlueChocolateDonut), new Object[]{
                ModItems.cookedDonut, ModItems.strawberryIcing, ModItems.pastryBag, ModItems.blueSprinkles, ModItems.shaker, ModItems.chocolateFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.strawberryBlueVanillaDonut), new Object[]{
                ModItems.cookedDonut, ModItems.strawberryIcing, ModItems.pastryBag, ModItems.blueSprinkles, ModItems.shaker, ModItems.vanillaFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.strawberryBlueCookieDoughDonut), new Object[]{
                ModItems.cookedDonut, ModItems.strawberryIcing, ModItems.pastryBag, ModItems.blueSprinkles, ModItems.shaker, ModItems.cookieDoughFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.strawberryBlueBrownieBatterDonut), new Object[]{
                ModItems.cookedDonut, ModItems.strawberryIcing, ModItems.pastryBag, ModItems.blueSprinkles, ModItems.shaker, ModItems.brownieBatterFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.strawberryRedNoneDonut), new Object[]{
                ModItems.cookedDonut, ModItems.strawberryIcing, ModItems.pastryBag, ModItems.redSprinkles, ModItems.shaker
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.strawberryRedStrawberryDonut), new Object[]{
                ModItems.cookedDonut, ModItems.strawberryIcing, ModItems.pastryBag, ModItems.redSprinkles, ModItems.shaker, ModItems.strawberryFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.strawberryRedChocolateDonut), new Object[]{
                ModItems.cookedDonut, ModItems.strawberryIcing, ModItems.pastryBag, ModItems.redSprinkles, ModItems.shaker, ModItems.chocolateFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.strawberryRedVanillaDonut), new Object[]{
                ModItems.cookedDonut, ModItems.strawberryIcing, ModItems.pastryBag, ModItems.redSprinkles, ModItems.shaker, ModItems.vanillaFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.strawberryRedCookieDoughDonut), new Object[]{
                ModItems.cookedDonut, ModItems.strawberryIcing, ModItems.pastryBag, ModItems.redSprinkles, ModItems.shaker, ModItems.cookieDoughFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.strawberryRedBrownieBatterDonut), new Object[]{
                ModItems.cookedDonut, ModItems.strawberryIcing, ModItems.pastryBag, ModItems.redSprinkles, ModItems.shaker, ModItems.brownieBatterFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.strawberryYellowNoneDonut), new Object[]{
                ModItems.cookedDonut, ModItems.strawberryIcing, ModItems.pastryBag, ModItems.yellowSprinkles, ModItems.shaker
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.strawberryYellowStrawberryDonut), new Object[]{
                ModItems.cookedDonut, ModItems.strawberryIcing, ModItems.pastryBag, ModItems.yellowSprinkles, ModItems.shaker, ModItems.strawberryFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.strawberryYellowChocolateDonut), new Object[]{
                ModItems.cookedDonut, ModItems.strawberryIcing, ModItems.pastryBag, ModItems.yellowSprinkles, ModItems.shaker, ModItems.chocolateFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.strawberryYellowVanillaDonut), new Object[]{
                ModItems.cookedDonut, ModItems.strawberryIcing, ModItems.pastryBag, ModItems.yellowSprinkles, ModItems.shaker, ModItems.vanillaFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.strawberryYellowCookieDoughDonut), new Object[]{
                ModItems.cookedDonut, ModItems.strawberryIcing, ModItems.pastryBag, ModItems.yellowSprinkles, ModItems.shaker, ModItems.cookieDoughFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.strawberryYellowBrownieBatterDonut), new Object[]{
                ModItems.cookedDonut, ModItems.strawberryIcing, ModItems.pastryBag, ModItems.yellowSprinkles, ModItems.shaker, ModItems.brownieBatterFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.strawberryOrangeNoneDonut), new Object[]{
                ModItems.cookedDonut, ModItems.strawberryIcing, ModItems.pastryBag, ModItems.orangeSprinkles, ModItems.shaker
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.strawberryOrangeStrawberryDonut), new Object[]{
                ModItems.cookedDonut, ModItems.strawberryIcing, ModItems.pastryBag, ModItems.orangeSprinkles, ModItems.shaker, ModItems.strawberryFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.strawberryOrangeChocolateDonut), new Object[]{
                ModItems.cookedDonut, ModItems.strawberryIcing, ModItems.pastryBag, ModItems.orangeSprinkles, ModItems.shaker, ModItems.chocolateFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.strawberryOrangeVanillaDonut), new Object[]{
                ModItems.cookedDonut, ModItems.strawberryIcing, ModItems.pastryBag, ModItems.orangeSprinkles, ModItems.shaker, ModItems.vanillaFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.strawberryOrangeCookieDoughDonut), new Object[]{
                ModItems.cookedDonut, ModItems.strawberryIcing, ModItems.pastryBag, ModItems.orangeSprinkles, ModItems.shaker, ModItems.cookieDoughFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.strawberryOrangeBrownieBatterDonut), new Object[]{
                ModItems.cookedDonut, ModItems.strawberryIcing, ModItems.pastryBag, ModItems.orangeSprinkles, ModItems.shaker, ModItems.brownieBatterFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.strawberryRainbowNoneDonut), new Object[]{
                ModItems.cookedDonut, ModItems.strawberryIcing, ModItems.pastryBag, ModItems.rainbowSprinkles, ModItems.shaker
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.strawberryRainbowStrawberryDonut), new Object[]{
                ModItems.cookedDonut, ModItems.strawberryIcing, ModItems.pastryBag, ModItems.rainbowSprinkles, ModItems.shaker, ModItems.strawberryFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.strawberryRainbowChocolateDonut), new Object[]{
                ModItems.cookedDonut, ModItems.strawberryIcing, ModItems.pastryBag, ModItems.rainbowSprinkles, ModItems.shaker, ModItems.chocolateFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.strawberryRainbowVanillaDonut), new Object[]{
                ModItems.cookedDonut, ModItems.strawberryIcing, ModItems.pastryBag, ModItems.rainbowSprinkles, ModItems.shaker, ModItems.vanillaFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.strawberryRainbowCookieDoughDonut), new Object[]{
                ModItems.cookedDonut, ModItems.strawberryIcing, ModItems.pastryBag, ModItems.rainbowSprinkles, ModItems.shaker, ModItems.cookieDoughFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.strawberryRainbowBrownieBatterDonut), new Object[]{
                ModItems.cookedDonut, ModItems.strawberryIcing, ModItems.pastryBag, ModItems.rainbowSprinkles, ModItems.shaker, ModItems.brownieBatterFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.chocolateNoneNoneDonut), new Object[]{
                ModItems.cookedDonut, ModItems.chocolateIcing, ModItems.pastryBag
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.chocolateNoneStrawberryDonut), new Object[]{
                ModItems.cookedDonut, ModItems.chocolateIcing, ModItems.pastryBag, ModItems.strawberryFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.chocolateNoneChocolateDonut), new Object[]{
                ModItems.cookedDonut, ModItems.chocolateIcing, ModItems.pastryBag, ModItems.chocolateFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.chocolateNoneVanillaDonut), new Object[]{
                ModItems.cookedDonut, ModItems.chocolateIcing, ModItems.pastryBag, ModItems.vanillaFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.chocolateNoneCookieDoughDonut), new Object[]{
                ModItems.cookedDonut, ModItems.chocolateIcing, ModItems.pastryBag, ModItems.cookieDoughFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.chocolateNoneBrownieBatterDonut), new Object[]{
                ModItems.cookedDonut, ModItems.chocolateIcing, ModItems.pastryBag, ModItems.brownieBatterFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.chocolateGreenNoneDonut), new Object[]{
                ModItems.cookedDonut, ModItems.chocolateIcing, ModItems.pastryBag, ModItems.greenSprinkles, ModItems.shaker
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.chocolateGreenStrawberryDonut), new Object[]{
                ModItems.cookedDonut, ModItems.chocolateIcing, ModItems.pastryBag, ModItems.greenSprinkles, ModItems.shaker, ModItems.strawberryFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.chocolateGreenChocolateDonut), new Object[]{
                ModItems.cookedDonut, ModItems.chocolateIcing, ModItems.pastryBag, ModItems.greenSprinkles, ModItems.shaker, ModItems.chocolateFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.chocolateGreenVanillaDonut), new Object[]{
                ModItems.cookedDonut, ModItems.chocolateIcing, ModItems.pastryBag, ModItems.greenSprinkles, ModItems.shaker, ModItems.vanillaFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.chocolateGreenCookieDoughDonut), new Object[]{
                ModItems.cookedDonut, ModItems.chocolateIcing, ModItems.pastryBag, ModItems.greenSprinkles, ModItems.shaker, ModItems.cookieDoughFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.chocolateGreenBrownieBatterDonut), new Object[]{
                ModItems.cookedDonut, ModItems.chocolateIcing, ModItems.pastryBag, ModItems.greenSprinkles, ModItems.shaker, ModItems.brownieBatterFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.chocolateBlueNoneDonut), new Object[]{
                ModItems.cookedDonut, ModItems.chocolateIcing, ModItems.pastryBag, ModItems.blueSprinkles, ModItems.shaker
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.chocolateBlueStrawberryDonut), new Object[]{
                ModItems.cookedDonut, ModItems.chocolateIcing, ModItems.pastryBag, ModItems.blueSprinkles, ModItems.shaker, ModItems.strawberryFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.chocolateBlueChocolateDonut), new Object[]{
                ModItems.cookedDonut, ModItems.chocolateIcing, ModItems.pastryBag, ModItems.blueSprinkles, ModItems.shaker, ModItems.chocolateFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.chocolateBlueVanillaDonut), new Object[]{
                ModItems.cookedDonut, ModItems.chocolateIcing, ModItems.pastryBag, ModItems.blueSprinkles, ModItems.shaker, ModItems.vanillaFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.chocolateBlueCookieDoughDonut), new Object[]{
                ModItems.cookedDonut, ModItems.chocolateIcing, ModItems.pastryBag, ModItems.blueSprinkles, ModItems.shaker, ModItems.cookieDoughFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.chocolateBlueBrownieBatterDonut), new Object[]{
                ModItems.cookedDonut, ModItems.chocolateIcing, ModItems.pastryBag, ModItems.blueSprinkles, ModItems.shaker, ModItems.brownieBatterFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.chocolateRedNoneDonut), new Object[]{
                ModItems.cookedDonut, ModItems.chocolateIcing, ModItems.pastryBag, ModItems.redSprinkles, ModItems.shaker
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.chocolateRedStrawberryDonut), new Object[]{
                ModItems.cookedDonut, ModItems.chocolateIcing, ModItems.pastryBag, ModItems.redSprinkles, ModItems.shaker, ModItems.strawberryFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.chocolateRedChocolateDonut), new Object[]{
                ModItems.cookedDonut, ModItems.chocolateIcing, ModItems.pastryBag, ModItems.redSprinkles, ModItems.shaker, ModItems.chocolateFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.chocolateRedVanillaDonut), new Object[]{
                ModItems.cookedDonut, ModItems.chocolateIcing, ModItems.pastryBag, ModItems.redSprinkles, ModItems.shaker, ModItems.vanillaFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.chocolateRedCookieDoughDonut), new Object[]{
                ModItems.cookedDonut, ModItems.chocolateIcing, ModItems.pastryBag, ModItems.redSprinkles, ModItems.shaker, ModItems.cookieDoughFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.chocolateRedBrownieBatterDonut), new Object[]{
                ModItems.cookedDonut, ModItems.chocolateIcing, ModItems.pastryBag, ModItems.redSprinkles, ModItems.shaker, ModItems.brownieBatterFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.chocolateYellowNoneDonut), new Object[]{
                ModItems.cookedDonut, ModItems.chocolateIcing, ModItems.pastryBag, ModItems.yellowSprinkles, ModItems.shaker
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.chocolateYellowStrawberryDonut), new Object[]{
                ModItems.cookedDonut, ModItems.chocolateIcing, ModItems.pastryBag, ModItems.yellowSprinkles, ModItems.shaker, ModItems.strawberryFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.chocolateYellowChocolateDonut), new Object[]{
                ModItems.cookedDonut, ModItems.chocolateIcing, ModItems.pastryBag, ModItems.yellowSprinkles, ModItems.shaker, ModItems.chocolateFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.chocolateYellowVanillaDonut), new Object[]{
                ModItems.cookedDonut, ModItems.chocolateIcing, ModItems.pastryBag, ModItems.yellowSprinkles, ModItems.shaker, ModItems.vanillaFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.chocolateYellowCookieDoughDonut), new Object[]{
                ModItems.cookedDonut, ModItems.chocolateIcing, ModItems.pastryBag, ModItems.yellowSprinkles, ModItems.shaker, ModItems.cookieDoughFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.chocolateYellowBrownieBatterDonut), new Object[]{
                ModItems.cookedDonut, ModItems.chocolateIcing, ModItems.pastryBag, ModItems.yellowSprinkles, ModItems.shaker, ModItems.brownieBatterFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.chocolateOrangeNoneDonut), new Object[]{
                ModItems.cookedDonut, ModItems.chocolateIcing, ModItems.pastryBag, ModItems.orangeSprinkles, ModItems.shaker
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.chocolateOrangeStrawberryDonut), new Object[]{
                ModItems.cookedDonut, ModItems.chocolateIcing, ModItems.pastryBag, ModItems.orangeSprinkles, ModItems.shaker, ModItems.strawberryFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.chocolateOrangeChocolateDonut), new Object[]{
                ModItems.cookedDonut, ModItems.chocolateIcing, ModItems.pastryBag, ModItems.orangeSprinkles, ModItems.shaker, ModItems.chocolateFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.chocolateOrangeVanillaDonut), new Object[]{
                ModItems.cookedDonut, ModItems.chocolateIcing, ModItems.pastryBag, ModItems.orangeSprinkles, ModItems.shaker, ModItems.vanillaFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.chocolateOrangeCookieDoughDonut), new Object[]{
                ModItems.cookedDonut, ModItems.chocolateIcing, ModItems.pastryBag, ModItems.orangeSprinkles, ModItems.shaker, ModItems.cookieDoughFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.chocolateOrangeBrownieBatterDonut), new Object[]{
                ModItems.cookedDonut, ModItems.chocolateIcing, ModItems.pastryBag, ModItems.orangeSprinkles, ModItems.shaker, ModItems.brownieBatterFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.chocolateRainbowNoneDonut), new Object[]{
                ModItems.cookedDonut, ModItems.chocolateIcing, ModItems.pastryBag, ModItems.rainbowSprinkles, ModItems.shaker
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.chocolateRainbowStrawberryDonut), new Object[]{
                ModItems.cookedDonut, ModItems.chocolateIcing, ModItems.pastryBag, ModItems.rainbowSprinkles, ModItems.shaker, ModItems.strawberryFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.chocolateRainbowChocolateDonut), new Object[]{
                ModItems.cookedDonut, ModItems.chocolateIcing, ModItems.pastryBag, ModItems.rainbowSprinkles, ModItems.shaker, ModItems.chocolateFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.chocolateRainbowVanillaDonut), new Object[]{
                ModItems.cookedDonut, ModItems.chocolateIcing, ModItems.pastryBag, ModItems.rainbowSprinkles, ModItems.shaker, ModItems.vanillaFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.chocolateRainbowCookieDoughDonut), new Object[]{
                ModItems.cookedDonut, ModItems.chocolateIcing, ModItems.pastryBag, ModItems.rainbowSprinkles, ModItems.shaker, ModItems.cookieDoughFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.chocolateRainbowBrownieBatterDonut), new Object[]{
                ModItems.cookedDonut, ModItems.chocolateIcing, ModItems.pastryBag, ModItems.rainbowSprinkles, ModItems.shaker, ModItems.brownieBatterFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.blueberryNoneNoneDonut), new Object[]{
                ModItems.cookedDonut, ModItems.blueberryIcing, ModItems.pastryBag
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.blueberryNoneStrawberryDonut), new Object[]{
                ModItems.cookedDonut, ModItems.blueberryIcing, ModItems.pastryBag, ModItems.strawberryFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.blueberryNoneChocolateDonut), new Object[]{
                ModItems.cookedDonut, ModItems.blueberryIcing, ModItems.pastryBag, ModItems.chocolateFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.blueberryNoneVanillaDonut), new Object[]{
                ModItems.cookedDonut, ModItems.blueberryIcing, ModItems.pastryBag, ModItems.vanillaFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.blueberryNoneCookieDoughDonut), new Object[]{
                ModItems.cookedDonut, ModItems.blueberryIcing, ModItems.pastryBag, ModItems.cookieDoughFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.blueberryNoneBrownieBatterDonut), new Object[]{
                ModItems.cookedDonut, ModItems.blueberryIcing, ModItems.pastryBag, ModItems.brownieBatterFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.blueberryGreenNoneDonut), new Object[]{
                ModItems.cookedDonut, ModItems.blueberryIcing, ModItems.pastryBag, ModItems.greenSprinkles, ModItems.shaker
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.blueberryGreenStrawberryDonut), new Object[]{
                ModItems.cookedDonut, ModItems.blueberryIcing, ModItems.pastryBag, ModItems.greenSprinkles, ModItems.shaker, ModItems.strawberryFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.blueberryGreenChocolateDonut), new Object[]{
                ModItems.cookedDonut, ModItems.blueberryIcing, ModItems.pastryBag, ModItems.greenSprinkles, ModItems.shaker, ModItems.chocolateFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.blueberryGreenVanillaDonut), new Object[]{
                ModItems.cookedDonut, ModItems.blueberryIcing, ModItems.pastryBag, ModItems.greenSprinkles, ModItems.shaker, ModItems.vanillaFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.blueberryGreenCookieDoughDonut), new Object[]{
                ModItems.cookedDonut, ModItems.blueberryIcing, ModItems.pastryBag, ModItems.greenSprinkles, ModItems.shaker, ModItems.cookieDoughFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.blueberryGreenBrownieBatterDonut), new Object[]{
                ModItems.cookedDonut, ModItems.blueberryIcing, ModItems.pastryBag, ModItems.greenSprinkles, ModItems.shaker, ModItems.brownieBatterFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.blueberryBlueNoneDonut), new Object[]{
                ModItems.cookedDonut, ModItems.blueberryIcing, ModItems.pastryBag, ModItems.blueSprinkles, ModItems.shaker
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.blueberryBlueStrawberryDonut), new Object[]{
                ModItems.cookedDonut, ModItems.blueberryIcing, ModItems.pastryBag, ModItems.blueSprinkles, ModItems.shaker, ModItems.strawberryFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.blueberryBlueChocolateDonut), new Object[]{
                ModItems.cookedDonut, ModItems.blueberryIcing, ModItems.pastryBag, ModItems.blueSprinkles, ModItems.shaker, ModItems.chocolateFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.blueberryBlueVanillaDonut), new Object[]{
                ModItems.cookedDonut, ModItems.blueberryIcing, ModItems.pastryBag, ModItems.blueSprinkles, ModItems.shaker, ModItems.vanillaFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.blueberryBlueCookieDoughDonut), new Object[]{
                ModItems.cookedDonut, ModItems.blueberryIcing, ModItems.pastryBag, ModItems.blueSprinkles, ModItems.shaker, ModItems.cookieDoughFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.blueberryBlueBrownieBatterDonut), new Object[]{
                ModItems.cookedDonut, ModItems.blueberryIcing, ModItems.pastryBag, ModItems.blueSprinkles, ModItems.shaker, ModItems.brownieBatterFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.blueberryRedNoneDonut), new Object[]{
                ModItems.cookedDonut, ModItems.blueberryIcing, ModItems.pastryBag, ModItems.redSprinkles, ModItems.shaker
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.blueberryRedStrawberryDonut), new Object[]{
                ModItems.cookedDonut, ModItems.blueberryIcing, ModItems.pastryBag, ModItems.redSprinkles, ModItems.shaker, ModItems.strawberryFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.blueberryRedChocolateDonut), new Object[]{
                ModItems.cookedDonut, ModItems.blueberryIcing, ModItems.pastryBag, ModItems.redSprinkles, ModItems.shaker, ModItems.chocolateFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.blueberryRedVanillaDonut), new Object[]{
                ModItems.cookedDonut, ModItems.blueberryIcing, ModItems.pastryBag, ModItems.redSprinkles, ModItems.shaker, ModItems.vanillaFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.blueberryRedCookieDoughDonut), new Object[]{
                ModItems.cookedDonut, ModItems.blueberryIcing, ModItems.pastryBag, ModItems.redSprinkles, ModItems.shaker, ModItems.cookieDoughFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.blueberryRedBrownieBatterDonut), new Object[]{
                ModItems.cookedDonut, ModItems.blueberryIcing, ModItems.pastryBag, ModItems.redSprinkles, ModItems.shaker, ModItems.brownieBatterFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.blueberryYellowNoneDonut), new Object[]{
                ModItems.cookedDonut, ModItems.blueberryIcing, ModItems.pastryBag, ModItems.yellowSprinkles, ModItems.shaker
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.blueberryYellowStrawberryDonut), new Object[]{
                ModItems.cookedDonut, ModItems.blueberryIcing, ModItems.pastryBag, ModItems.yellowSprinkles, ModItems.shaker, ModItems.strawberryFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.blueberryYellowChocolateDonut), new Object[]{
                ModItems.cookedDonut, ModItems.blueberryIcing, ModItems.pastryBag, ModItems.yellowSprinkles, ModItems.shaker, ModItems.chocolateFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.blueberryYellowVanillaDonut), new Object[]{
                ModItems.cookedDonut, ModItems.blueberryIcing, ModItems.pastryBag, ModItems.yellowSprinkles, ModItems.shaker, ModItems.vanillaFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.blueberryYellowCookieDoughDonut), new Object[]{
                ModItems.cookedDonut, ModItems.blueberryIcing, ModItems.pastryBag, ModItems.yellowSprinkles, ModItems.shaker, ModItems.cookieDoughFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.blueberryYellowBrownieBatterDonut), new Object[]{
                ModItems.cookedDonut, ModItems.blueberryIcing, ModItems.pastryBag, ModItems.yellowSprinkles, ModItems.shaker, ModItems.brownieBatterFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.blueberryOrangeNoneDonut), new Object[]{
                ModItems.cookedDonut, ModItems.blueberryIcing, ModItems.pastryBag, ModItems.orangeSprinkles, ModItems.shaker
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.blueberryOrangeStrawberryDonut), new Object[]{
                ModItems.cookedDonut, ModItems.blueberryIcing, ModItems.pastryBag, ModItems.orangeSprinkles, ModItems.shaker, ModItems.strawberryFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.blueberryOrangeChocolateDonut), new Object[]{
                ModItems.cookedDonut, ModItems.blueberryIcing, ModItems.pastryBag, ModItems.orangeSprinkles, ModItems.shaker, ModItems.chocolateFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.blueberryOrangeVanillaDonut), new Object[]{
                ModItems.cookedDonut, ModItems.blueberryIcing, ModItems.pastryBag, ModItems.orangeSprinkles, ModItems.shaker, ModItems.vanillaFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.blueberryOrangeCookieDoughDonut), new Object[]{
                ModItems.cookedDonut, ModItems.blueberryIcing, ModItems.pastryBag, ModItems.orangeSprinkles, ModItems.shaker, ModItems.cookieDoughFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.blueberryOrangeBrownieBatterDonut), new Object[]{
                ModItems.cookedDonut, ModItems.blueberryIcing, ModItems.pastryBag, ModItems.orangeSprinkles, ModItems.shaker, ModItems.brownieBatterFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.blueberryRainbowNoneDonut), new Object[]{
                ModItems.cookedDonut, ModItems.blueberryIcing, ModItems.pastryBag, ModItems.rainbowSprinkles, ModItems.shaker
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.blueberryRainbowStrawberryDonut), new Object[]{
                ModItems.cookedDonut, ModItems.blueberryIcing, ModItems.pastryBag, ModItems.rainbowSprinkles, ModItems.shaker, ModItems.strawberryFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.blueberryRainbowChocolateDonut), new Object[]{
                ModItems.cookedDonut, ModItems.blueberryIcing, ModItems.pastryBag, ModItems.rainbowSprinkles, ModItems.shaker, ModItems.chocolateFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.blueberryRainbowVanillaDonut), new Object[]{
                ModItems.cookedDonut, ModItems.blueberryIcing, ModItems.pastryBag, ModItems.rainbowSprinkles, ModItems.shaker, ModItems.vanillaFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.blueberryRainbowCookieDoughDonut), new Object[]{
                ModItems.cookedDonut, ModItems.blueberryIcing, ModItems.pastryBag, ModItems.rainbowSprinkles, ModItems.shaker, ModItems.cookieDoughFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.blueberryRainbowBrownieBatterDonut), new Object[]{
                ModItems.cookedDonut, ModItems.blueberryIcing, ModItems.pastryBag, ModItems.rainbowSprinkles, ModItems.shaker, ModItems.brownieBatterFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.vanillaNoneNoneDonut), new Object[]{
                ModItems.cookedDonut, ModItems.vanillaIcing, ModItems.pastryBag
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.vanillaNoneStrawberryDonut), new Object[]{
                ModItems.cookedDonut, ModItems.vanillaIcing, ModItems.pastryBag, ModItems.strawberryFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.vanillaNoneChocolateDonut), new Object[]{
                ModItems.cookedDonut, ModItems.vanillaIcing, ModItems.pastryBag, ModItems.chocolateFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.vanillaNoneVanillaDonut), new Object[]{
                ModItems.cookedDonut, ModItems.vanillaIcing, ModItems.pastryBag, ModItems.vanillaFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.vanillaNoneCookieDoughDonut), new Object[]{
                ModItems.cookedDonut, ModItems.vanillaIcing, ModItems.pastryBag, ModItems.cookieDoughFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.vanillaNoneBrownieBatterDonut), new Object[]{
                ModItems.cookedDonut, ModItems.vanillaIcing, ModItems.pastryBag, ModItems.brownieBatterFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.vanillaGreenNoneDonut), new Object[]{
                ModItems.cookedDonut, ModItems.vanillaIcing, ModItems.pastryBag, ModItems.greenSprinkles, ModItems.shaker
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.vanillaGreenStrawberryDonut), new Object[]{
                ModItems.cookedDonut, ModItems.vanillaIcing, ModItems.pastryBag, ModItems.greenSprinkles, ModItems.shaker, ModItems.strawberryFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.vanillaGreenChocolateDonut), new Object[]{
                ModItems.cookedDonut, ModItems.vanillaIcing, ModItems.pastryBag, ModItems.greenSprinkles, ModItems.shaker, ModItems.chocolateFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.vanillaGreenVanillaDonut), new Object[]{
                ModItems.cookedDonut, ModItems.vanillaIcing, ModItems.pastryBag, ModItems.greenSprinkles, ModItems.shaker, ModItems.vanillaFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.vanillaGreenCookieDoughDonut), new Object[]{
                ModItems.cookedDonut, ModItems.vanillaIcing, ModItems.pastryBag, ModItems.greenSprinkles, ModItems.shaker, ModItems.cookieDoughFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.vanillaGreenBrownieBatterDonut), new Object[]{
                ModItems.cookedDonut, ModItems.vanillaIcing, ModItems.pastryBag, ModItems.greenSprinkles, ModItems.shaker, ModItems.brownieBatterFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.vanillaBlueNoneDonut), new Object[]{
                ModItems.cookedDonut, ModItems.vanillaIcing, ModItems.pastryBag, ModItems.blueSprinkles, ModItems.shaker
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.vanillaBlueStrawberryDonut), new Object[]{
                ModItems.cookedDonut, ModItems.vanillaIcing, ModItems.pastryBag, ModItems.blueSprinkles, ModItems.shaker, ModItems.strawberryFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.vanillaBlueChocolateDonut), new Object[]{
                ModItems.cookedDonut, ModItems.vanillaIcing, ModItems.pastryBag, ModItems.blueSprinkles, ModItems.shaker, ModItems.chocolateFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.vanillaBlueVanillaDonut), new Object[]{
                ModItems.cookedDonut, ModItems.vanillaIcing, ModItems.pastryBag, ModItems.blueSprinkles, ModItems.shaker, ModItems.vanillaFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.vanillaBlueCookieDoughDonut), new Object[]{
                ModItems.cookedDonut, ModItems.vanillaIcing, ModItems.pastryBag, ModItems.blueSprinkles, ModItems.shaker, ModItems.cookieDoughFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.vanillaBlueBrownieBatterDonut), new Object[]{
                ModItems.cookedDonut, ModItems.vanillaIcing, ModItems.pastryBag, ModItems.blueSprinkles, ModItems.shaker, ModItems.brownieBatterFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.vanillaRedNoneDonut), new Object[]{
                ModItems.cookedDonut, ModItems.vanillaIcing, ModItems.pastryBag, ModItems.redSprinkles, ModItems.shaker
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.vanillaRedStrawberryDonut), new Object[]{
                ModItems.cookedDonut, ModItems.vanillaIcing, ModItems.pastryBag, ModItems.redSprinkles, ModItems.shaker, ModItems.strawberryFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.vanillaRedChocolateDonut), new Object[]{
                ModItems.cookedDonut, ModItems.vanillaIcing, ModItems.pastryBag, ModItems.redSprinkles, ModItems.shaker, ModItems.chocolateFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.vanillaRedVanillaDonut), new Object[]{
                ModItems.cookedDonut, ModItems.vanillaIcing, ModItems.pastryBag, ModItems.redSprinkles, ModItems.shaker, ModItems.vanillaFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.vanillaRedCookieDoughDonut), new Object[]{
                ModItems.cookedDonut, ModItems.vanillaIcing, ModItems.pastryBag, ModItems.redSprinkles, ModItems.shaker, ModItems.cookieDoughFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.vanillaRedBrownieBatterDonut), new Object[]{
                ModItems.cookedDonut, ModItems.vanillaIcing, ModItems.pastryBag, ModItems.redSprinkles, ModItems.shaker, ModItems.brownieBatterFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.vanillaYellowNoneDonut), new Object[]{
                ModItems.cookedDonut, ModItems.vanillaIcing, ModItems.pastryBag, ModItems.yellowSprinkles, ModItems.shaker
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.vanillaYellowStrawberryDonut), new Object[]{
                ModItems.cookedDonut, ModItems.vanillaIcing, ModItems.pastryBag, ModItems.yellowSprinkles, ModItems.shaker, ModItems.strawberryFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.vanillaYellowChocolateDonut), new Object[]{
                ModItems.cookedDonut, ModItems.vanillaIcing, ModItems.pastryBag, ModItems.yellowSprinkles, ModItems.shaker, ModItems.chocolateFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.vanillaYellowVanillaDonut), new Object[]{
                ModItems.cookedDonut, ModItems.vanillaIcing, ModItems.pastryBag, ModItems.yellowSprinkles, ModItems.shaker, ModItems.vanillaFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.vanillaYellowCookieDoughDonut), new Object[]{
                ModItems.cookedDonut, ModItems.vanillaIcing, ModItems.pastryBag, ModItems.yellowSprinkles, ModItems.shaker, ModItems.cookieDoughFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.vanillaYellowBrownieBatterDonut), new Object[]{
                ModItems.cookedDonut, ModItems.vanillaIcing, ModItems.pastryBag, ModItems.yellowSprinkles, ModItems.shaker, ModItems.brownieBatterFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.vanillaOrangeNoneDonut), new Object[]{
                ModItems.cookedDonut, ModItems.vanillaIcing, ModItems.pastryBag, ModItems.orangeSprinkles, ModItems.shaker
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.vanillaOrangeStrawberryDonut), new Object[]{
                ModItems.cookedDonut, ModItems.vanillaIcing, ModItems.pastryBag, ModItems.orangeSprinkles, ModItems.shaker, ModItems.strawberryFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.vanillaOrangeChocolateDonut), new Object[]{
                ModItems.cookedDonut, ModItems.vanillaIcing, ModItems.pastryBag, ModItems.orangeSprinkles, ModItems.shaker, ModItems.chocolateFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.vanillaOrangeVanillaDonut), new Object[]{
                ModItems.cookedDonut, ModItems.vanillaIcing, ModItems.pastryBag, ModItems.orangeSprinkles, ModItems.shaker, ModItems.vanillaFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.vanillaOrangeCookieDoughDonut), new Object[]{
                ModItems.cookedDonut, ModItems.vanillaIcing, ModItems.pastryBag, ModItems.orangeSprinkles, ModItems.shaker, ModItems.cookieDoughFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.vanillaOrangeBrownieBatterDonut), new Object[]{
                ModItems.cookedDonut, ModItems.vanillaIcing, ModItems.pastryBag, ModItems.orangeSprinkles, ModItems.shaker, ModItems.brownieBatterFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.vanillaRainbowNoneDonut), new Object[]{
                ModItems.cookedDonut, ModItems.vanillaIcing, ModItems.pastryBag, ModItems.rainbowSprinkles, ModItems.shaker
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.vanillaRainbowStrawberryDonut), new Object[]{
                ModItems.cookedDonut, ModItems.vanillaIcing, ModItems.pastryBag, ModItems.rainbowSprinkles, ModItems.shaker, ModItems.strawberryFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.vanillaRainbowChocolateDonut), new Object[]{
                ModItems.cookedDonut, ModItems.vanillaIcing, ModItems.pastryBag, ModItems.rainbowSprinkles, ModItems.shaker, ModItems.chocolateFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.vanillaRainbowVanillaDonut), new Object[]{
                ModItems.cookedDonut, ModItems.vanillaIcing, ModItems.pastryBag, ModItems.rainbowSprinkles, ModItems.shaker, ModItems.vanillaFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.vanillaRainbowCookieDoughDonut), new Object[]{
                ModItems.cookedDonut, ModItems.vanillaIcing, ModItems.pastryBag, ModItems.rainbowSprinkles, ModItems.shaker, ModItems.cookieDoughFilling, ModItems.fillingTube
        });

        GameRegistry.addShapelessRecipe( new ItemStack( ModItems.vanillaRainbowBrownieBatterDonut), new Object[]{
                ModItems.cookedDonut, ModItems.vanillaIcing, ModItems.pastryBag, ModItems.rainbowSprinkles, ModItems.shaker, ModItems.brownieBatterFilling, ModItems.fillingTube
        });

        /*
        * end - Auto generated by DonutCombos.py
        */
    }
}
