package com.munchicken.multidonutsmod.items;

import com.munchicken.multidonutsmod.help.RegisterHelper;
import net.minecraft.item.Item;
import net.minecraft.item.ItemFood;

public class ModItems {

    //public static ItemFood donut;
    //public static ItemFood strawberryYellowBrownieDonut;
    //public static ItemFood noneNoneNoneDonut;
    public static Item dough;
    public static Item rollingPin;
    public static Item flatDough;
    public static Item cutter;
    public static Item rawDonut;
    public static Item cookedDonut;
    public static Item pastryBag;
    public static ItemFood strawberry;
    public static ItemFood blueberry;
    public static Item vanillaBean;
    public static Item shaker;
    public static ItemFood strawberryIcing;
    public static ItemFood chocolateIcing;
    public static ItemFood blueberryIcing;
    public static ItemFood vanillaIcing;
    public static ItemFood greenSprinkles;
    public static ItemFood blueSprinkles;
    public static ItemFood redSprinkles;
    public static ItemFood yellowSprinkles;
    public static ItemFood orangeSprinkles;
    public static ItemFood rainbowSprinkles;
    public static ItemFood strawberryFilling;
    public static ItemFood chocolateFilling;
    public static ItemFood vanillaFilling;
    public static ItemFood cookieDoughFilling;
    public static ItemFood brownieBatterFilling;
    public static Item fillingTube;

    /*
    * begin - Auto generated by DonutCombos.py
    */
    public static ItemFood noneNoneNoneDonut;
    public static ItemFood noneNoneStrawberryDonut;
    public static ItemFood noneNoneChocolateDonut;
    public static ItemFood noneNoneVanillaDonut;
    public static ItemFood noneNoneCookieDoughDonut;
    public static ItemFood noneNoneBrownieBatterDonut;
    public static ItemFood noneGreenNoneDonut;
    public static ItemFood noneGreenStrawberryDonut;
    public static ItemFood noneGreenChocolateDonut;
    public static ItemFood noneGreenVanillaDonut;
    public static ItemFood noneGreenCookieDoughDonut;
    public static ItemFood noneGreenBrownieBatterDonut;
    public static ItemFood noneBlueNoneDonut;
    public static ItemFood noneBlueStrawberryDonut;
    public static ItemFood noneBlueChocolateDonut;
    public static ItemFood noneBlueVanillaDonut;
    public static ItemFood noneBlueCookieDoughDonut;
    public static ItemFood noneBlueBrownieBatterDonut;
    public static ItemFood noneRedNoneDonut;
    public static ItemFood noneRedStrawberryDonut;
    public static ItemFood noneRedChocolateDonut;
    public static ItemFood noneRedVanillaDonut;
    public static ItemFood noneRedCookieDoughDonut;
    public static ItemFood noneRedBrownieBatterDonut;
    public static ItemFood noneYellowNoneDonut;
    public static ItemFood noneYellowStrawberryDonut;
    public static ItemFood noneYellowChocolateDonut;
    public static ItemFood noneYellowVanillaDonut;
    public static ItemFood noneYellowCookieDoughDonut;
    public static ItemFood noneYellowBrownieBatterDonut;
    public static ItemFood noneOrangeNoneDonut;
    public static ItemFood noneOrangeStrawberryDonut;
    public static ItemFood noneOrangeChocolateDonut;
    public static ItemFood noneOrangeVanillaDonut;
    public static ItemFood noneOrangeCookieDoughDonut;
    public static ItemFood noneOrangeBrownieBatterDonut;
    public static ItemFood noneRainbowNoneDonut;
    public static ItemFood noneRainbowStrawberryDonut;
    public static ItemFood noneRainbowChocolateDonut;
    public static ItemFood noneRainbowVanillaDonut;
    public static ItemFood noneRainbowCookieDoughDonut;
    public static ItemFood noneRainbowBrownieBatterDonut;
    public static ItemFood strawberryNoneNoneDonut;
    public static ItemFood strawberryNoneStrawberryDonut;
    public static ItemFood strawberryNoneChocolateDonut;
    public static ItemFood strawberryNoneVanillaDonut;
    public static ItemFood strawberryNoneCookieDoughDonut;
    public static ItemFood strawberryNoneBrownieBatterDonut;
    public static ItemFood strawberryGreenNoneDonut;
    public static ItemFood strawberryGreenStrawberryDonut;
    public static ItemFood strawberryGreenChocolateDonut;
    public static ItemFood strawberryGreenVanillaDonut;
    public static ItemFood strawberryGreenCookieDoughDonut;
    public static ItemFood strawberryGreenBrownieBatterDonut;
    public static ItemFood strawberryBlueNoneDonut;
    public static ItemFood strawberryBlueStrawberryDonut;
    public static ItemFood strawberryBlueChocolateDonut;
    public static ItemFood strawberryBlueVanillaDonut;
    public static ItemFood strawberryBlueCookieDoughDonut;
    public static ItemFood strawberryBlueBrownieBatterDonut;
    public static ItemFood strawberryRedNoneDonut;
    public static ItemFood strawberryRedStrawberryDonut;
    public static ItemFood strawberryRedChocolateDonut;
    public static ItemFood strawberryRedVanillaDonut;
    public static ItemFood strawberryRedCookieDoughDonut;
    public static ItemFood strawberryRedBrownieBatterDonut;
    public static ItemFood strawberryYellowNoneDonut;
    public static ItemFood strawberryYellowStrawberryDonut;
    public static ItemFood strawberryYellowChocolateDonut;
    public static ItemFood strawberryYellowVanillaDonut;
    public static ItemFood strawberryYellowCookieDoughDonut;
    public static ItemFood strawberryYellowBrownieBatterDonut;
    public static ItemFood strawberryOrangeNoneDonut;
    public static ItemFood strawberryOrangeStrawberryDonut;
    public static ItemFood strawberryOrangeChocolateDonut;
    public static ItemFood strawberryOrangeVanillaDonut;
    public static ItemFood strawberryOrangeCookieDoughDonut;
    public static ItemFood strawberryOrangeBrownieBatterDonut;
    public static ItemFood strawberryRainbowNoneDonut;
    public static ItemFood strawberryRainbowStrawberryDonut;
    public static ItemFood strawberryRainbowChocolateDonut;
    public static ItemFood strawberryRainbowVanillaDonut;
    public static ItemFood strawberryRainbowCookieDoughDonut;
    public static ItemFood strawberryRainbowBrownieBatterDonut;
    public static ItemFood chocolateNoneNoneDonut;
    public static ItemFood chocolateNoneStrawberryDonut;
    public static ItemFood chocolateNoneChocolateDonut;
    public static ItemFood chocolateNoneVanillaDonut;
    public static ItemFood chocolateNoneCookieDoughDonut;
    public static ItemFood chocolateNoneBrownieBatterDonut;
    public static ItemFood chocolateGreenNoneDonut;
    public static ItemFood chocolateGreenStrawberryDonut;
    public static ItemFood chocolateGreenChocolateDonut;
    public static ItemFood chocolateGreenVanillaDonut;
    public static ItemFood chocolateGreenCookieDoughDonut;
    public static ItemFood chocolateGreenBrownieBatterDonut;
    public static ItemFood chocolateBlueNoneDonut;
    public static ItemFood chocolateBlueStrawberryDonut;
    public static ItemFood chocolateBlueChocolateDonut;
    public static ItemFood chocolateBlueVanillaDonut;
    public static ItemFood chocolateBlueCookieDoughDonut;
    public static ItemFood chocolateBlueBrownieBatterDonut;
    public static ItemFood chocolateRedNoneDonut;
    public static ItemFood chocolateRedStrawberryDonut;
    public static ItemFood chocolateRedChocolateDonut;
    public static ItemFood chocolateRedVanillaDonut;
    public static ItemFood chocolateRedCookieDoughDonut;
    public static ItemFood chocolateRedBrownieBatterDonut;
    public static ItemFood chocolateYellowNoneDonut;
    public static ItemFood chocolateYellowStrawberryDonut;
    public static ItemFood chocolateYellowChocolateDonut;
    public static ItemFood chocolateYellowVanillaDonut;
    public static ItemFood chocolateYellowCookieDoughDonut;
    public static ItemFood chocolateYellowBrownieBatterDonut;
    public static ItemFood chocolateOrangeNoneDonut;
    public static ItemFood chocolateOrangeStrawberryDonut;
    public static ItemFood chocolateOrangeChocolateDonut;
    public static ItemFood chocolateOrangeVanillaDonut;
    public static ItemFood chocolateOrangeCookieDoughDonut;
    public static ItemFood chocolateOrangeBrownieBatterDonut;
    public static ItemFood chocolateRainbowNoneDonut;
    public static ItemFood chocolateRainbowStrawberryDonut;
    public static ItemFood chocolateRainbowChocolateDonut;
    public static ItemFood chocolateRainbowVanillaDonut;
    public static ItemFood chocolateRainbowCookieDoughDonut;
    public static ItemFood chocolateRainbowBrownieBatterDonut;
    public static ItemFood blueberryNoneNoneDonut;
    public static ItemFood blueberryNoneStrawberryDonut;
    public static ItemFood blueberryNoneChocolateDonut;
    public static ItemFood blueberryNoneVanillaDonut;
    public static ItemFood blueberryNoneCookieDoughDonut;
    public static ItemFood blueberryNoneBrownieBatterDonut;
    public static ItemFood blueberryGreenNoneDonut;
    public static ItemFood blueberryGreenStrawberryDonut;
    public static ItemFood blueberryGreenChocolateDonut;
    public static ItemFood blueberryGreenVanillaDonut;
    public static ItemFood blueberryGreenCookieDoughDonut;
    public static ItemFood blueberryGreenBrownieBatterDonut;
    public static ItemFood blueberryBlueNoneDonut;
    public static ItemFood blueberryBlueStrawberryDonut;
    public static ItemFood blueberryBlueChocolateDonut;
    public static ItemFood blueberryBlueVanillaDonut;
    public static ItemFood blueberryBlueCookieDoughDonut;
    public static ItemFood blueberryBlueBrownieBatterDonut;
    public static ItemFood blueberryRedNoneDonut;
    public static ItemFood blueberryRedStrawberryDonut;
    public static ItemFood blueberryRedChocolateDonut;
    public static ItemFood blueberryRedVanillaDonut;
    public static ItemFood blueberryRedCookieDoughDonut;
    public static ItemFood blueberryRedBrownieBatterDonut;
    public static ItemFood blueberryYellowNoneDonut;
    public static ItemFood blueberryYellowStrawberryDonut;
    public static ItemFood blueberryYellowChocolateDonut;
    public static ItemFood blueberryYellowVanillaDonut;
    public static ItemFood blueberryYellowCookieDoughDonut;
    public static ItemFood blueberryYellowBrownieBatterDonut;
    public static ItemFood blueberryOrangeNoneDonut;
    public static ItemFood blueberryOrangeStrawberryDonut;
    public static ItemFood blueberryOrangeChocolateDonut;
    public static ItemFood blueberryOrangeVanillaDonut;
    public static ItemFood blueberryOrangeCookieDoughDonut;
    public static ItemFood blueberryOrangeBrownieBatterDonut;
    public static ItemFood blueberryRainbowNoneDonut;
    public static ItemFood blueberryRainbowStrawberryDonut;
    public static ItemFood blueberryRainbowChocolateDonut;
    public static ItemFood blueberryRainbowVanillaDonut;
    public static ItemFood blueberryRainbowCookieDoughDonut;
    public static ItemFood blueberryRainbowBrownieBatterDonut;
    public static ItemFood vanillaNoneNoneDonut;
    public static ItemFood vanillaNoneStrawberryDonut;
    public static ItemFood vanillaNoneChocolateDonut;
    public static ItemFood vanillaNoneVanillaDonut;
    public static ItemFood vanillaNoneCookieDoughDonut;
    public static ItemFood vanillaNoneBrownieBatterDonut;
    public static ItemFood vanillaGreenNoneDonut;
    public static ItemFood vanillaGreenStrawberryDonut;
    public static ItemFood vanillaGreenChocolateDonut;
    public static ItemFood vanillaGreenVanillaDonut;
    public static ItemFood vanillaGreenCookieDoughDonut;
    public static ItemFood vanillaGreenBrownieBatterDonut;
    public static ItemFood vanillaBlueNoneDonut;
    public static ItemFood vanillaBlueStrawberryDonut;
    public static ItemFood vanillaBlueChocolateDonut;
    public static ItemFood vanillaBlueVanillaDonut;
    public static ItemFood vanillaBlueCookieDoughDonut;
    public static ItemFood vanillaBlueBrownieBatterDonut;
    public static ItemFood vanillaRedNoneDonut;
    public static ItemFood vanillaRedStrawberryDonut;
    public static ItemFood vanillaRedChocolateDonut;
    public static ItemFood vanillaRedVanillaDonut;
    public static ItemFood vanillaRedCookieDoughDonut;
    public static ItemFood vanillaRedBrownieBatterDonut;
    public static ItemFood vanillaYellowNoneDonut;
    public static ItemFood vanillaYellowStrawberryDonut;
    public static ItemFood vanillaYellowChocolateDonut;
    public static ItemFood vanillaYellowVanillaDonut;
    public static ItemFood vanillaYellowCookieDoughDonut;
    public static ItemFood vanillaYellowBrownieBatterDonut;
    public static ItemFood vanillaOrangeNoneDonut;
    public static ItemFood vanillaOrangeStrawberryDonut;
    public static ItemFood vanillaOrangeChocolateDonut;
    public static ItemFood vanillaOrangeVanillaDonut;
    public static ItemFood vanillaOrangeCookieDoughDonut;
    public static ItemFood vanillaOrangeBrownieBatterDonut;
    public static ItemFood vanillaRainbowNoneDonut;
    public static ItemFood vanillaRainbowStrawberryDonut;
    public static ItemFood vanillaRainbowChocolateDonut;
    public static ItemFood vanillaRainbowVanillaDonut;
    public static ItemFood vanillaRainbowCookieDoughDonut;
    public static ItemFood vanillaRainbowBrownieBatterDonut;
    /*
     * end - Auto generated by DonutCombos.py
     */

    public static void loadItems(){

        //donut = new Donut();
        //RegisterHelper.registerItem(donut);

        //strawberryYellowBrownieDonut = new Donut(Donut.Icing.STRAWBERRY,Donut.Sprinkle.YELLOW, Donut.Fill.BROWNIE);
        //RegisterHelper.registerItem(strawberryYellowBrownieDonut);

        //noneNoneNoneDonut = new Donut(Donut.Icing.NONE,Donut.Sprinkle.NONE, Donut.Fill.NONE);
        //RegisterHelper.registerItem(noneNoneNoneDonut);

        dough = new Dough();
        RegisterHelper.registerItem(dough);

        rollingPin = new RollingPin();
        RegisterHelper.registerItem(rollingPin);

        flatDough = new FlatDough();
        RegisterHelper.registerItem(flatDough);

        cutter = new Cutter();
        RegisterHelper.registerItem(cutter);

        rawDonut = new RawDonut();
        RegisterHelper.registerItem(rawDonut);

        cookedDonut = new CookedDonut();
        RegisterHelper.registerItem(cookedDonut);

        pastryBag = new PastryBag();
        RegisterHelper.registerItem(pastryBag);

        strawberry = new Strawberry();
        RegisterHelper.registerItem(strawberry);

        blueberry = new Blueberry();
        RegisterHelper.registerItem(blueberry);

        vanillaBean = new VanillaBean();
        RegisterHelper.registerItem(vanillaBean);

        shaker = new Shaker();
        RegisterHelper.registerItem(shaker);

        strawberryIcing = new StrawberryIcing();
        RegisterHelper.registerItem(strawberryIcing);

        chocolateIcing = new ChocolateIcing();
        RegisterHelper.registerItem(chocolateIcing);

        blueberryIcing = new BlueberryIcing();
        RegisterHelper.registerItem(blueberryIcing);

        vanillaIcing = new VanillaIcing();
        RegisterHelper.registerItem(vanillaIcing);

        greenSprinkles = new GreenSprinkles();
        RegisterHelper.registerItem(greenSprinkles);

        blueSprinkles = new BlueSprinkles();
        RegisterHelper.registerItem(blueSprinkles);

        redSprinkles = new RedSprinkles();
        RegisterHelper.registerItem(redSprinkles);

        yellowSprinkles = new YellowSprinkles();
        RegisterHelper.registerItem(yellowSprinkles);

        orangeSprinkles = new OrangeSprinkles();
        RegisterHelper.registerItem(orangeSprinkles);

        rainbowSprinkles = new RainbowSprinkles();
        RegisterHelper.registerItem(rainbowSprinkles);

        strawberryFilling = new StrawberryFilling();
        RegisterHelper.registerItem(strawberryFilling);

        chocolateFilling = new ChocolateFilling();
        RegisterHelper.registerItem(chocolateFilling);

        vanillaFilling = new VanillaFilling();
        RegisterHelper.registerItem(vanillaFilling);

        cookieDoughFilling = new CookieDoughFilling();
        RegisterHelper.registerItem(cookieDoughFilling);

        brownieBatterFilling = new BrownieBatterFilling();
        RegisterHelper.registerItem(brownieBatterFilling);

        fillingTube = new FillingTube();
        RegisterHelper.registerItem(fillingTube);

        /*
        * begin - Auto generated by DonutCombos.py
        */
        noneNoneNoneDonut = new Donut(Donut.Icing.NONE, Donut.Sprinkle.NONE, Donut.Fill.NONE);
        RegisterHelper.registerItem(noneNoneNoneDonut );

        noneNoneStrawberryDonut = new Donut(Donut.Icing.NONE, Donut.Sprinkle.NONE, Donut.Fill.STRAWBERRY);
        RegisterHelper.registerItem(noneNoneStrawberryDonut );

        noneNoneChocolateDonut = new Donut(Donut.Icing.NONE, Donut.Sprinkle.NONE, Donut.Fill.CHOCOLATE);
        RegisterHelper.registerItem(noneNoneChocolateDonut );

        noneNoneVanillaDonut = new Donut(Donut.Icing.NONE, Donut.Sprinkle.NONE, Donut.Fill.VANILLA);
        RegisterHelper.registerItem(noneNoneVanillaDonut );

        noneNoneCookieDoughDonut = new Donut(Donut.Icing.NONE, Donut.Sprinkle.NONE, Donut.Fill.COOKIEDOUGH);
        RegisterHelper.registerItem(noneNoneCookieDoughDonut );

        noneNoneBrownieBatterDonut = new Donut(Donut.Icing.NONE, Donut.Sprinkle.NONE, Donut.Fill.BROWNIEBATTER);
        RegisterHelper.registerItem(noneNoneBrownieBatterDonut );

        noneGreenNoneDonut = new Donut(Donut.Icing.NONE, Donut.Sprinkle.GREEN, Donut.Fill.NONE);
        RegisterHelper.registerItem(noneGreenNoneDonut );

        noneGreenStrawberryDonut = new Donut(Donut.Icing.NONE, Donut.Sprinkle.GREEN, Donut.Fill.STRAWBERRY);
        RegisterHelper.registerItem(noneGreenStrawberryDonut );

        noneGreenChocolateDonut = new Donut(Donut.Icing.NONE, Donut.Sprinkle.GREEN, Donut.Fill.CHOCOLATE);
        RegisterHelper.registerItem(noneGreenChocolateDonut );

        noneGreenVanillaDonut = new Donut(Donut.Icing.NONE, Donut.Sprinkle.GREEN, Donut.Fill.VANILLA);
        RegisterHelper.registerItem(noneGreenVanillaDonut );

        noneGreenCookieDoughDonut = new Donut(Donut.Icing.NONE, Donut.Sprinkle.GREEN, Donut.Fill.COOKIEDOUGH);
        RegisterHelper.registerItem(noneGreenCookieDoughDonut );

        noneGreenBrownieBatterDonut = new Donut(Donut.Icing.NONE, Donut.Sprinkle.GREEN, Donut.Fill.BROWNIEBATTER);
        RegisterHelper.registerItem(noneGreenBrownieBatterDonut );

        noneBlueNoneDonut = new Donut(Donut.Icing.NONE, Donut.Sprinkle.BLUE, Donut.Fill.NONE);
        RegisterHelper.registerItem(noneBlueNoneDonut );

        noneBlueStrawberryDonut = new Donut(Donut.Icing.NONE, Donut.Sprinkle.BLUE, Donut.Fill.STRAWBERRY);
        RegisterHelper.registerItem(noneBlueStrawberryDonut );

        noneBlueChocolateDonut = new Donut(Donut.Icing.NONE, Donut.Sprinkle.BLUE, Donut.Fill.CHOCOLATE);
        RegisterHelper.registerItem(noneBlueChocolateDonut );

        noneBlueVanillaDonut = new Donut(Donut.Icing.NONE, Donut.Sprinkle.BLUE, Donut.Fill.VANILLA);
        RegisterHelper.registerItem(noneBlueVanillaDonut );

        noneBlueCookieDoughDonut = new Donut(Donut.Icing.NONE, Donut.Sprinkle.BLUE, Donut.Fill.COOKIEDOUGH);
        RegisterHelper.registerItem(noneBlueCookieDoughDonut );

        noneBlueBrownieBatterDonut = new Donut(Donut.Icing.NONE, Donut.Sprinkle.BLUE, Donut.Fill.BROWNIEBATTER);
        RegisterHelper.registerItem(noneBlueBrownieBatterDonut );

        noneRedNoneDonut = new Donut(Donut.Icing.NONE, Donut.Sprinkle.RED, Donut.Fill.NONE);
        RegisterHelper.registerItem(noneRedNoneDonut );

        noneRedStrawberryDonut = new Donut(Donut.Icing.NONE, Donut.Sprinkle.RED, Donut.Fill.STRAWBERRY);
        RegisterHelper.registerItem(noneRedStrawberryDonut );

        noneRedChocolateDonut = new Donut(Donut.Icing.NONE, Donut.Sprinkle.RED, Donut.Fill.CHOCOLATE);
        RegisterHelper.registerItem(noneRedChocolateDonut );

        noneRedVanillaDonut = new Donut(Donut.Icing.NONE, Donut.Sprinkle.RED, Donut.Fill.VANILLA);
        RegisterHelper.registerItem(noneRedVanillaDonut );

        noneRedCookieDoughDonut = new Donut(Donut.Icing.NONE, Donut.Sprinkle.RED, Donut.Fill.COOKIEDOUGH);
        RegisterHelper.registerItem(noneRedCookieDoughDonut );

        noneRedBrownieBatterDonut = new Donut(Donut.Icing.NONE, Donut.Sprinkle.RED, Donut.Fill.BROWNIEBATTER);
        RegisterHelper.registerItem(noneRedBrownieBatterDonut );

        noneYellowNoneDonut = new Donut(Donut.Icing.NONE, Donut.Sprinkle.YELLOW, Donut.Fill.NONE);
        RegisterHelper.registerItem(noneYellowNoneDonut );

        noneYellowStrawberryDonut = new Donut(Donut.Icing.NONE, Donut.Sprinkle.YELLOW, Donut.Fill.STRAWBERRY);
        RegisterHelper.registerItem(noneYellowStrawberryDonut );

        noneYellowChocolateDonut = new Donut(Donut.Icing.NONE, Donut.Sprinkle.YELLOW, Donut.Fill.CHOCOLATE);
        RegisterHelper.registerItem(noneYellowChocolateDonut );

        noneYellowVanillaDonut = new Donut(Donut.Icing.NONE, Donut.Sprinkle.YELLOW, Donut.Fill.VANILLA);
        RegisterHelper.registerItem(noneYellowVanillaDonut );

        noneYellowCookieDoughDonut = new Donut(Donut.Icing.NONE, Donut.Sprinkle.YELLOW, Donut.Fill.COOKIEDOUGH);
        RegisterHelper.registerItem(noneYellowCookieDoughDonut );

        noneYellowBrownieBatterDonut = new Donut(Donut.Icing.NONE, Donut.Sprinkle.YELLOW, Donut.Fill.BROWNIEBATTER);
        RegisterHelper.registerItem(noneYellowBrownieBatterDonut );

        noneOrangeNoneDonut = new Donut(Donut.Icing.NONE, Donut.Sprinkle.ORANGE, Donut.Fill.NONE);
        RegisterHelper.registerItem(noneOrangeNoneDonut );

        noneOrangeStrawberryDonut = new Donut(Donut.Icing.NONE, Donut.Sprinkle.ORANGE, Donut.Fill.STRAWBERRY);
        RegisterHelper.registerItem(noneOrangeStrawberryDonut );

        noneOrangeChocolateDonut = new Donut(Donut.Icing.NONE, Donut.Sprinkle.ORANGE, Donut.Fill.CHOCOLATE);
        RegisterHelper.registerItem(noneOrangeChocolateDonut );

        noneOrangeVanillaDonut = new Donut(Donut.Icing.NONE, Donut.Sprinkle.ORANGE, Donut.Fill.VANILLA);
        RegisterHelper.registerItem(noneOrangeVanillaDonut );

        noneOrangeCookieDoughDonut = new Donut(Donut.Icing.NONE, Donut.Sprinkle.ORANGE, Donut.Fill.COOKIEDOUGH);
        RegisterHelper.registerItem(noneOrangeCookieDoughDonut );

        noneOrangeBrownieBatterDonut = new Donut(Donut.Icing.NONE, Donut.Sprinkle.ORANGE, Donut.Fill.BROWNIEBATTER);
        RegisterHelper.registerItem(noneOrangeBrownieBatterDonut );

        noneRainbowNoneDonut = new Donut(Donut.Icing.NONE, Donut.Sprinkle.RAINBOW, Donut.Fill.NONE);
        RegisterHelper.registerItem(noneRainbowNoneDonut );

        noneRainbowStrawberryDonut = new Donut(Donut.Icing.NONE, Donut.Sprinkle.RAINBOW, Donut.Fill.STRAWBERRY);
        RegisterHelper.registerItem(noneRainbowStrawberryDonut );

        noneRainbowChocolateDonut = new Donut(Donut.Icing.NONE, Donut.Sprinkle.RAINBOW, Donut.Fill.CHOCOLATE);
        RegisterHelper.registerItem(noneRainbowChocolateDonut );

        noneRainbowVanillaDonut = new Donut(Donut.Icing.NONE, Donut.Sprinkle.RAINBOW, Donut.Fill.VANILLA);
        RegisterHelper.registerItem(noneRainbowVanillaDonut );

        noneRainbowCookieDoughDonut = new Donut(Donut.Icing.NONE, Donut.Sprinkle.RAINBOW, Donut.Fill.COOKIEDOUGH);
        RegisterHelper.registerItem(noneRainbowCookieDoughDonut );

        noneRainbowBrownieBatterDonut = new Donut(Donut.Icing.NONE, Donut.Sprinkle.RAINBOW, Donut.Fill.BROWNIEBATTER);
        RegisterHelper.registerItem(noneRainbowBrownieBatterDonut );

        strawberryNoneNoneDonut = new Donut(Donut.Icing.STRAWBERRY, Donut.Sprinkle.NONE, Donut.Fill.NONE);
        RegisterHelper.registerItem(strawberryNoneNoneDonut );

        strawberryNoneStrawberryDonut = new Donut(Donut.Icing.STRAWBERRY, Donut.Sprinkle.NONE, Donut.Fill.STRAWBERRY);
        RegisterHelper.registerItem(strawberryNoneStrawberryDonut );

        strawberryNoneChocolateDonut = new Donut(Donut.Icing.STRAWBERRY, Donut.Sprinkle.NONE, Donut.Fill.CHOCOLATE);
        RegisterHelper.registerItem(strawberryNoneChocolateDonut );

        strawberryNoneVanillaDonut = new Donut(Donut.Icing.STRAWBERRY, Donut.Sprinkle.NONE, Donut.Fill.VANILLA);
        RegisterHelper.registerItem(strawberryNoneVanillaDonut );

        strawberryNoneCookieDoughDonut = new Donut(Donut.Icing.STRAWBERRY, Donut.Sprinkle.NONE, Donut.Fill.COOKIEDOUGH);
        RegisterHelper.registerItem(strawberryNoneCookieDoughDonut );

        strawberryNoneBrownieBatterDonut = new Donut(Donut.Icing.STRAWBERRY, Donut.Sprinkle.NONE, Donut.Fill.BROWNIEBATTER);
        RegisterHelper.registerItem(strawberryNoneBrownieBatterDonut );

        strawberryGreenNoneDonut = new Donut(Donut.Icing.STRAWBERRY, Donut.Sprinkle.GREEN, Donut.Fill.NONE);
        RegisterHelper.registerItem(strawberryGreenNoneDonut );

        strawberryGreenStrawberryDonut = new Donut(Donut.Icing.STRAWBERRY, Donut.Sprinkle.GREEN, Donut.Fill.STRAWBERRY);
        RegisterHelper.registerItem(strawberryGreenStrawberryDonut );

        strawberryGreenChocolateDonut = new Donut(Donut.Icing.STRAWBERRY, Donut.Sprinkle.GREEN, Donut.Fill.CHOCOLATE);
        RegisterHelper.registerItem(strawberryGreenChocolateDonut );

        strawberryGreenVanillaDonut = new Donut(Donut.Icing.STRAWBERRY, Donut.Sprinkle.GREEN, Donut.Fill.VANILLA);
        RegisterHelper.registerItem(strawberryGreenVanillaDonut );

        strawberryGreenCookieDoughDonut = new Donut(Donut.Icing.STRAWBERRY, Donut.Sprinkle.GREEN, Donut.Fill.COOKIEDOUGH);
        RegisterHelper.registerItem(strawberryGreenCookieDoughDonut );

        strawberryGreenBrownieBatterDonut = new Donut(Donut.Icing.STRAWBERRY, Donut.Sprinkle.GREEN, Donut.Fill.BROWNIEBATTER);
        RegisterHelper.registerItem(strawberryGreenBrownieBatterDonut );

        strawberryBlueNoneDonut = new Donut(Donut.Icing.STRAWBERRY, Donut.Sprinkle.BLUE, Donut.Fill.NONE);
        RegisterHelper.registerItem(strawberryBlueNoneDonut );

        strawberryBlueStrawberryDonut = new Donut(Donut.Icing.STRAWBERRY, Donut.Sprinkle.BLUE, Donut.Fill.STRAWBERRY);
        RegisterHelper.registerItem(strawberryBlueStrawberryDonut );

        strawberryBlueChocolateDonut = new Donut(Donut.Icing.STRAWBERRY, Donut.Sprinkle.BLUE, Donut.Fill.CHOCOLATE);
        RegisterHelper.registerItem(strawberryBlueChocolateDonut );

        strawberryBlueVanillaDonut = new Donut(Donut.Icing.STRAWBERRY, Donut.Sprinkle.BLUE, Donut.Fill.VANILLA);
        RegisterHelper.registerItem(strawberryBlueVanillaDonut );

        strawberryBlueCookieDoughDonut = new Donut(Donut.Icing.STRAWBERRY, Donut.Sprinkle.BLUE, Donut.Fill.COOKIEDOUGH);
        RegisterHelper.registerItem(strawberryBlueCookieDoughDonut );

        strawberryBlueBrownieBatterDonut = new Donut(Donut.Icing.STRAWBERRY, Donut.Sprinkle.BLUE, Donut.Fill.BROWNIEBATTER);
        RegisterHelper.registerItem(strawberryBlueBrownieBatterDonut );

        strawberryRedNoneDonut = new Donut(Donut.Icing.STRAWBERRY, Donut.Sprinkle.RED, Donut.Fill.NONE);
        RegisterHelper.registerItem(strawberryRedNoneDonut );

        strawberryRedStrawberryDonut = new Donut(Donut.Icing.STRAWBERRY, Donut.Sprinkle.RED, Donut.Fill.STRAWBERRY);
        RegisterHelper.registerItem(strawberryRedStrawberryDonut );

        strawberryRedChocolateDonut = new Donut(Donut.Icing.STRAWBERRY, Donut.Sprinkle.RED, Donut.Fill.CHOCOLATE);
        RegisterHelper.registerItem(strawberryRedChocolateDonut );

        strawberryRedVanillaDonut = new Donut(Donut.Icing.STRAWBERRY, Donut.Sprinkle.RED, Donut.Fill.VANILLA);
        RegisterHelper.registerItem(strawberryRedVanillaDonut );

        strawberryRedCookieDoughDonut = new Donut(Donut.Icing.STRAWBERRY, Donut.Sprinkle.RED, Donut.Fill.COOKIEDOUGH);
        RegisterHelper.registerItem(strawberryRedCookieDoughDonut );

        strawberryRedBrownieBatterDonut = new Donut(Donut.Icing.STRAWBERRY, Donut.Sprinkle.RED, Donut.Fill.BROWNIEBATTER);
        RegisterHelper.registerItem(strawberryRedBrownieBatterDonut );

        strawberryYellowNoneDonut = new Donut(Donut.Icing.STRAWBERRY, Donut.Sprinkle.YELLOW, Donut.Fill.NONE);
        RegisterHelper.registerItem(strawberryYellowNoneDonut );

        strawberryYellowStrawberryDonut = new Donut(Donut.Icing.STRAWBERRY, Donut.Sprinkle.YELLOW, Donut.Fill.STRAWBERRY);
        RegisterHelper.registerItem(strawberryYellowStrawberryDonut );

        strawberryYellowChocolateDonut = new Donut(Donut.Icing.STRAWBERRY, Donut.Sprinkle.YELLOW, Donut.Fill.CHOCOLATE);
        RegisterHelper.registerItem(strawberryYellowChocolateDonut );

        strawberryYellowVanillaDonut = new Donut(Donut.Icing.STRAWBERRY, Donut.Sprinkle.YELLOW, Donut.Fill.VANILLA);
        RegisterHelper.registerItem(strawberryYellowVanillaDonut );

        strawberryYellowCookieDoughDonut = new Donut(Donut.Icing.STRAWBERRY, Donut.Sprinkle.YELLOW, Donut.Fill.COOKIEDOUGH);
        RegisterHelper.registerItem(strawberryYellowCookieDoughDonut );

        strawberryYellowBrownieBatterDonut = new Donut(Donut.Icing.STRAWBERRY, Donut.Sprinkle.YELLOW, Donut.Fill.BROWNIEBATTER);
        RegisterHelper.registerItem(strawberryYellowBrownieBatterDonut );

        strawberryOrangeNoneDonut = new Donut(Donut.Icing.STRAWBERRY, Donut.Sprinkle.ORANGE, Donut.Fill.NONE);
        RegisterHelper.registerItem(strawberryOrangeNoneDonut );

        strawberryOrangeStrawberryDonut = new Donut(Donut.Icing.STRAWBERRY, Donut.Sprinkle.ORANGE, Donut.Fill.STRAWBERRY);
        RegisterHelper.registerItem(strawberryOrangeStrawberryDonut );

        strawberryOrangeChocolateDonut = new Donut(Donut.Icing.STRAWBERRY, Donut.Sprinkle.ORANGE, Donut.Fill.CHOCOLATE);
        RegisterHelper.registerItem(strawberryOrangeChocolateDonut );

        strawberryOrangeVanillaDonut = new Donut(Donut.Icing.STRAWBERRY, Donut.Sprinkle.ORANGE, Donut.Fill.VANILLA);
        RegisterHelper.registerItem(strawberryOrangeVanillaDonut );

        strawberryOrangeCookieDoughDonut = new Donut(Donut.Icing.STRAWBERRY, Donut.Sprinkle.ORANGE, Donut.Fill.COOKIEDOUGH);
        RegisterHelper.registerItem(strawberryOrangeCookieDoughDonut );

        strawberryOrangeBrownieBatterDonut = new Donut(Donut.Icing.STRAWBERRY, Donut.Sprinkle.ORANGE, Donut.Fill.BROWNIEBATTER);
        RegisterHelper.registerItem(strawberryOrangeBrownieBatterDonut );

        strawberryRainbowNoneDonut = new Donut(Donut.Icing.STRAWBERRY, Donut.Sprinkle.RAINBOW, Donut.Fill.NONE);
        RegisterHelper.registerItem(strawberryRainbowNoneDonut );

        strawberryRainbowStrawberryDonut = new Donut(Donut.Icing.STRAWBERRY, Donut.Sprinkle.RAINBOW, Donut.Fill.STRAWBERRY);
        RegisterHelper.registerItem(strawberryRainbowStrawberryDonut );

        strawberryRainbowChocolateDonut = new Donut(Donut.Icing.STRAWBERRY, Donut.Sprinkle.RAINBOW, Donut.Fill.CHOCOLATE);
        RegisterHelper.registerItem(strawberryRainbowChocolateDonut );

        strawberryRainbowVanillaDonut = new Donut(Donut.Icing.STRAWBERRY, Donut.Sprinkle.RAINBOW, Donut.Fill.VANILLA);
        RegisterHelper.registerItem(strawberryRainbowVanillaDonut );

        strawberryRainbowCookieDoughDonut = new Donut(Donut.Icing.STRAWBERRY, Donut.Sprinkle.RAINBOW, Donut.Fill.COOKIEDOUGH);
        RegisterHelper.registerItem(strawberryRainbowCookieDoughDonut );

        strawberryRainbowBrownieBatterDonut = new Donut(Donut.Icing.STRAWBERRY, Donut.Sprinkle.RAINBOW, Donut.Fill.BROWNIEBATTER);
        RegisterHelper.registerItem(strawberryRainbowBrownieBatterDonut );

        chocolateNoneNoneDonut = new Donut(Donut.Icing.CHOCOLATE, Donut.Sprinkle.NONE, Donut.Fill.NONE);
        RegisterHelper.registerItem(chocolateNoneNoneDonut );

        chocolateNoneStrawberryDonut = new Donut(Donut.Icing.CHOCOLATE, Donut.Sprinkle.NONE, Donut.Fill.STRAWBERRY);
        RegisterHelper.registerItem(chocolateNoneStrawberryDonut );

        chocolateNoneChocolateDonut = new Donut(Donut.Icing.CHOCOLATE, Donut.Sprinkle.NONE, Donut.Fill.CHOCOLATE);
        RegisterHelper.registerItem(chocolateNoneChocolateDonut );

        chocolateNoneVanillaDonut = new Donut(Donut.Icing.CHOCOLATE, Donut.Sprinkle.NONE, Donut.Fill.VANILLA);
        RegisterHelper.registerItem(chocolateNoneVanillaDonut );

        chocolateNoneCookieDoughDonut = new Donut(Donut.Icing.CHOCOLATE, Donut.Sprinkle.NONE, Donut.Fill.COOKIEDOUGH);
        RegisterHelper.registerItem(chocolateNoneCookieDoughDonut );

        chocolateNoneBrownieBatterDonut = new Donut(Donut.Icing.CHOCOLATE, Donut.Sprinkle.NONE, Donut.Fill.BROWNIEBATTER);
        RegisterHelper.registerItem(chocolateNoneBrownieBatterDonut );

        chocolateGreenNoneDonut = new Donut(Donut.Icing.CHOCOLATE, Donut.Sprinkle.GREEN, Donut.Fill.NONE);
        RegisterHelper.registerItem(chocolateGreenNoneDonut );

        chocolateGreenStrawberryDonut = new Donut(Donut.Icing.CHOCOLATE, Donut.Sprinkle.GREEN, Donut.Fill.STRAWBERRY);
        RegisterHelper.registerItem(chocolateGreenStrawberryDonut );

        chocolateGreenChocolateDonut = new Donut(Donut.Icing.CHOCOLATE, Donut.Sprinkle.GREEN, Donut.Fill.CHOCOLATE);
        RegisterHelper.registerItem(chocolateGreenChocolateDonut );

        chocolateGreenVanillaDonut = new Donut(Donut.Icing.CHOCOLATE, Donut.Sprinkle.GREEN, Donut.Fill.VANILLA);
        RegisterHelper.registerItem(chocolateGreenVanillaDonut );

        chocolateGreenCookieDoughDonut = new Donut(Donut.Icing.CHOCOLATE, Donut.Sprinkle.GREEN, Donut.Fill.COOKIEDOUGH);
        RegisterHelper.registerItem(chocolateGreenCookieDoughDonut );

        chocolateGreenBrownieBatterDonut = new Donut(Donut.Icing.CHOCOLATE, Donut.Sprinkle.GREEN, Donut.Fill.BROWNIEBATTER);
        RegisterHelper.registerItem(chocolateGreenBrownieBatterDonut );

        chocolateBlueNoneDonut = new Donut(Donut.Icing.CHOCOLATE, Donut.Sprinkle.BLUE, Donut.Fill.NONE);
        RegisterHelper.registerItem(chocolateBlueNoneDonut );

        chocolateBlueStrawberryDonut = new Donut(Donut.Icing.CHOCOLATE, Donut.Sprinkle.BLUE, Donut.Fill.STRAWBERRY);
        RegisterHelper.registerItem(chocolateBlueStrawberryDonut );

        chocolateBlueChocolateDonut = new Donut(Donut.Icing.CHOCOLATE, Donut.Sprinkle.BLUE, Donut.Fill.CHOCOLATE);
        RegisterHelper.registerItem(chocolateBlueChocolateDonut );

        chocolateBlueVanillaDonut = new Donut(Donut.Icing.CHOCOLATE, Donut.Sprinkle.BLUE, Donut.Fill.VANILLA);
        RegisterHelper.registerItem(chocolateBlueVanillaDonut );

        chocolateBlueCookieDoughDonut = new Donut(Donut.Icing.CHOCOLATE, Donut.Sprinkle.BLUE, Donut.Fill.COOKIEDOUGH);
        RegisterHelper.registerItem(chocolateBlueCookieDoughDonut );

        chocolateBlueBrownieBatterDonut = new Donut(Donut.Icing.CHOCOLATE, Donut.Sprinkle.BLUE, Donut.Fill.BROWNIEBATTER);
        RegisterHelper.registerItem(chocolateBlueBrownieBatterDonut );

        chocolateRedNoneDonut = new Donut(Donut.Icing.CHOCOLATE, Donut.Sprinkle.RED, Donut.Fill.NONE);
        RegisterHelper.registerItem(chocolateRedNoneDonut );

        chocolateRedStrawberryDonut = new Donut(Donut.Icing.CHOCOLATE, Donut.Sprinkle.RED, Donut.Fill.STRAWBERRY);
        RegisterHelper.registerItem(chocolateRedStrawberryDonut );

        chocolateRedChocolateDonut = new Donut(Donut.Icing.CHOCOLATE, Donut.Sprinkle.RED, Donut.Fill.CHOCOLATE);
        RegisterHelper.registerItem(chocolateRedChocolateDonut );

        chocolateRedVanillaDonut = new Donut(Donut.Icing.CHOCOLATE, Donut.Sprinkle.RED, Donut.Fill.VANILLA);
        RegisterHelper.registerItem(chocolateRedVanillaDonut );

        chocolateRedCookieDoughDonut = new Donut(Donut.Icing.CHOCOLATE, Donut.Sprinkle.RED, Donut.Fill.COOKIEDOUGH);
        RegisterHelper.registerItem(chocolateRedCookieDoughDonut );

        chocolateRedBrownieBatterDonut = new Donut(Donut.Icing.CHOCOLATE, Donut.Sprinkle.RED, Donut.Fill.BROWNIEBATTER);
        RegisterHelper.registerItem(chocolateRedBrownieBatterDonut );

        chocolateYellowNoneDonut = new Donut(Donut.Icing.CHOCOLATE, Donut.Sprinkle.YELLOW, Donut.Fill.NONE);
        RegisterHelper.registerItem(chocolateYellowNoneDonut );

        chocolateYellowStrawberryDonut = new Donut(Donut.Icing.CHOCOLATE, Donut.Sprinkle.YELLOW, Donut.Fill.STRAWBERRY);
        RegisterHelper.registerItem(chocolateYellowStrawberryDonut );

        chocolateYellowChocolateDonut = new Donut(Donut.Icing.CHOCOLATE, Donut.Sprinkle.YELLOW, Donut.Fill.CHOCOLATE);
        RegisterHelper.registerItem(chocolateYellowChocolateDonut );

        chocolateYellowVanillaDonut = new Donut(Donut.Icing.CHOCOLATE, Donut.Sprinkle.YELLOW, Donut.Fill.VANILLA);
        RegisterHelper.registerItem(chocolateYellowVanillaDonut );

        chocolateYellowCookieDoughDonut = new Donut(Donut.Icing.CHOCOLATE, Donut.Sprinkle.YELLOW, Donut.Fill.COOKIEDOUGH);
        RegisterHelper.registerItem(chocolateYellowCookieDoughDonut );

        chocolateYellowBrownieBatterDonut = new Donut(Donut.Icing.CHOCOLATE, Donut.Sprinkle.YELLOW, Donut.Fill.BROWNIEBATTER);
        RegisterHelper.registerItem(chocolateYellowBrownieBatterDonut );

        chocolateOrangeNoneDonut = new Donut(Donut.Icing.CHOCOLATE, Donut.Sprinkle.ORANGE, Donut.Fill.NONE);
        RegisterHelper.registerItem(chocolateOrangeNoneDonut );

        chocolateOrangeStrawberryDonut = new Donut(Donut.Icing.CHOCOLATE, Donut.Sprinkle.ORANGE, Donut.Fill.STRAWBERRY);
        RegisterHelper.registerItem(chocolateOrangeStrawberryDonut );

        chocolateOrangeChocolateDonut = new Donut(Donut.Icing.CHOCOLATE, Donut.Sprinkle.ORANGE, Donut.Fill.CHOCOLATE);
        RegisterHelper.registerItem(chocolateOrangeChocolateDonut );

        chocolateOrangeVanillaDonut = new Donut(Donut.Icing.CHOCOLATE, Donut.Sprinkle.ORANGE, Donut.Fill.VANILLA);
        RegisterHelper.registerItem(chocolateOrangeVanillaDonut );

        chocolateOrangeCookieDoughDonut = new Donut(Donut.Icing.CHOCOLATE, Donut.Sprinkle.ORANGE, Donut.Fill.COOKIEDOUGH);
        RegisterHelper.registerItem(chocolateOrangeCookieDoughDonut );

        chocolateOrangeBrownieBatterDonut = new Donut(Donut.Icing.CHOCOLATE, Donut.Sprinkle.ORANGE, Donut.Fill.BROWNIEBATTER);
        RegisterHelper.registerItem(chocolateOrangeBrownieBatterDonut );

        chocolateRainbowNoneDonut = new Donut(Donut.Icing.CHOCOLATE, Donut.Sprinkle.RAINBOW, Donut.Fill.NONE);
        RegisterHelper.registerItem(chocolateRainbowNoneDonut );

        chocolateRainbowStrawberryDonut = new Donut(Donut.Icing.CHOCOLATE, Donut.Sprinkle.RAINBOW, Donut.Fill.STRAWBERRY);
        RegisterHelper.registerItem(chocolateRainbowStrawberryDonut );

        chocolateRainbowChocolateDonut = new Donut(Donut.Icing.CHOCOLATE, Donut.Sprinkle.RAINBOW, Donut.Fill.CHOCOLATE);
        RegisterHelper.registerItem(chocolateRainbowChocolateDonut );

        chocolateRainbowVanillaDonut = new Donut(Donut.Icing.CHOCOLATE, Donut.Sprinkle.RAINBOW, Donut.Fill.VANILLA);
        RegisterHelper.registerItem(chocolateRainbowVanillaDonut );

        chocolateRainbowCookieDoughDonut = new Donut(Donut.Icing.CHOCOLATE, Donut.Sprinkle.RAINBOW, Donut.Fill.COOKIEDOUGH);
        RegisterHelper.registerItem(chocolateRainbowCookieDoughDonut );

        chocolateRainbowBrownieBatterDonut = new Donut(Donut.Icing.CHOCOLATE, Donut.Sprinkle.RAINBOW, Donut.Fill.BROWNIEBATTER);
        RegisterHelper.registerItem(chocolateRainbowBrownieBatterDonut );

        blueberryNoneNoneDonut = new Donut(Donut.Icing.BLUEBERRY, Donut.Sprinkle.NONE, Donut.Fill.NONE);
        RegisterHelper.registerItem(blueberryNoneNoneDonut );

        blueberryNoneStrawberryDonut = new Donut(Donut.Icing.BLUEBERRY, Donut.Sprinkle.NONE, Donut.Fill.STRAWBERRY);
        RegisterHelper.registerItem(blueberryNoneStrawberryDonut );

        blueberryNoneChocolateDonut = new Donut(Donut.Icing.BLUEBERRY, Donut.Sprinkle.NONE, Donut.Fill.CHOCOLATE);
        RegisterHelper.registerItem(blueberryNoneChocolateDonut );

        blueberryNoneVanillaDonut = new Donut(Donut.Icing.BLUEBERRY, Donut.Sprinkle.NONE, Donut.Fill.VANILLA);
        RegisterHelper.registerItem(blueberryNoneVanillaDonut );

        blueberryNoneCookieDoughDonut = new Donut(Donut.Icing.BLUEBERRY, Donut.Sprinkle.NONE, Donut.Fill.COOKIEDOUGH);
        RegisterHelper.registerItem(blueberryNoneCookieDoughDonut );

        blueberryNoneBrownieBatterDonut = new Donut(Donut.Icing.BLUEBERRY, Donut.Sprinkle.NONE, Donut.Fill.BROWNIEBATTER);
        RegisterHelper.registerItem(blueberryNoneBrownieBatterDonut );

        blueberryGreenNoneDonut = new Donut(Donut.Icing.BLUEBERRY, Donut.Sprinkle.GREEN, Donut.Fill.NONE);
        RegisterHelper.registerItem(blueberryGreenNoneDonut );

        blueberryGreenStrawberryDonut = new Donut(Donut.Icing.BLUEBERRY, Donut.Sprinkle.GREEN, Donut.Fill.STRAWBERRY);
        RegisterHelper.registerItem(blueberryGreenStrawberryDonut );

        blueberryGreenChocolateDonut = new Donut(Donut.Icing.BLUEBERRY, Donut.Sprinkle.GREEN, Donut.Fill.CHOCOLATE);
        RegisterHelper.registerItem(blueberryGreenChocolateDonut );

        blueberryGreenVanillaDonut = new Donut(Donut.Icing.BLUEBERRY, Donut.Sprinkle.GREEN, Donut.Fill.VANILLA);
        RegisterHelper.registerItem(blueberryGreenVanillaDonut );

        blueberryGreenCookieDoughDonut = new Donut(Donut.Icing.BLUEBERRY, Donut.Sprinkle.GREEN, Donut.Fill.COOKIEDOUGH);
        RegisterHelper.registerItem(blueberryGreenCookieDoughDonut );

        blueberryGreenBrownieBatterDonut = new Donut(Donut.Icing.BLUEBERRY, Donut.Sprinkle.GREEN, Donut.Fill.BROWNIEBATTER);
        RegisterHelper.registerItem(blueberryGreenBrownieBatterDonut );

        blueberryBlueNoneDonut = new Donut(Donut.Icing.BLUEBERRY, Donut.Sprinkle.BLUE, Donut.Fill.NONE);
        RegisterHelper.registerItem(blueberryBlueNoneDonut );

        blueberryBlueStrawberryDonut = new Donut(Donut.Icing.BLUEBERRY, Donut.Sprinkle.BLUE, Donut.Fill.STRAWBERRY);
        RegisterHelper.registerItem(blueberryBlueStrawberryDonut );

        blueberryBlueChocolateDonut = new Donut(Donut.Icing.BLUEBERRY, Donut.Sprinkle.BLUE, Donut.Fill.CHOCOLATE);
        RegisterHelper.registerItem(blueberryBlueChocolateDonut );

        blueberryBlueVanillaDonut = new Donut(Donut.Icing.BLUEBERRY, Donut.Sprinkle.BLUE, Donut.Fill.VANILLA);
        RegisterHelper.registerItem(blueberryBlueVanillaDonut );

        blueberryBlueCookieDoughDonut = new Donut(Donut.Icing.BLUEBERRY, Donut.Sprinkle.BLUE, Donut.Fill.COOKIEDOUGH);
        RegisterHelper.registerItem(blueberryBlueCookieDoughDonut );

        blueberryBlueBrownieBatterDonut = new Donut(Donut.Icing.BLUEBERRY, Donut.Sprinkle.BLUE, Donut.Fill.BROWNIEBATTER);
        RegisterHelper.registerItem(blueberryBlueBrownieBatterDonut );

        blueberryRedNoneDonut = new Donut(Donut.Icing.BLUEBERRY, Donut.Sprinkle.RED, Donut.Fill.NONE);
        RegisterHelper.registerItem(blueberryRedNoneDonut );

        blueberryRedStrawberryDonut = new Donut(Donut.Icing.BLUEBERRY, Donut.Sprinkle.RED, Donut.Fill.STRAWBERRY);
        RegisterHelper.registerItem(blueberryRedStrawberryDonut );

        blueberryRedChocolateDonut = new Donut(Donut.Icing.BLUEBERRY, Donut.Sprinkle.RED, Donut.Fill.CHOCOLATE);
        RegisterHelper.registerItem(blueberryRedChocolateDonut );

        blueberryRedVanillaDonut = new Donut(Donut.Icing.BLUEBERRY, Donut.Sprinkle.RED, Donut.Fill.VANILLA);
        RegisterHelper.registerItem(blueberryRedVanillaDonut );

        blueberryRedCookieDoughDonut = new Donut(Donut.Icing.BLUEBERRY, Donut.Sprinkle.RED, Donut.Fill.COOKIEDOUGH);
        RegisterHelper.registerItem(blueberryRedCookieDoughDonut );

        blueberryRedBrownieBatterDonut = new Donut(Donut.Icing.BLUEBERRY, Donut.Sprinkle.RED, Donut.Fill.BROWNIEBATTER);
        RegisterHelper.registerItem(blueberryRedBrownieBatterDonut );

        blueberryYellowNoneDonut = new Donut(Donut.Icing.BLUEBERRY, Donut.Sprinkle.YELLOW, Donut.Fill.NONE);
        RegisterHelper.registerItem(blueberryYellowNoneDonut );

        blueberryYellowStrawberryDonut = new Donut(Donut.Icing.BLUEBERRY, Donut.Sprinkle.YELLOW, Donut.Fill.STRAWBERRY);
        RegisterHelper.registerItem(blueberryYellowStrawberryDonut );

        blueberryYellowChocolateDonut = new Donut(Donut.Icing.BLUEBERRY, Donut.Sprinkle.YELLOW, Donut.Fill.CHOCOLATE);
        RegisterHelper.registerItem(blueberryYellowChocolateDonut );

        blueberryYellowVanillaDonut = new Donut(Donut.Icing.BLUEBERRY, Donut.Sprinkle.YELLOW, Donut.Fill.VANILLA);
        RegisterHelper.registerItem(blueberryYellowVanillaDonut );

        blueberryYellowCookieDoughDonut = new Donut(Donut.Icing.BLUEBERRY, Donut.Sprinkle.YELLOW, Donut.Fill.COOKIEDOUGH);
        RegisterHelper.registerItem(blueberryYellowCookieDoughDonut );

        blueberryYellowBrownieBatterDonut = new Donut(Donut.Icing.BLUEBERRY, Donut.Sprinkle.YELLOW, Donut.Fill.BROWNIEBATTER);
        RegisterHelper.registerItem(blueberryYellowBrownieBatterDonut );

        blueberryOrangeNoneDonut = new Donut(Donut.Icing.BLUEBERRY, Donut.Sprinkle.ORANGE, Donut.Fill.NONE);
        RegisterHelper.registerItem(blueberryOrangeNoneDonut );

        blueberryOrangeStrawberryDonut = new Donut(Donut.Icing.BLUEBERRY, Donut.Sprinkle.ORANGE, Donut.Fill.STRAWBERRY);
        RegisterHelper.registerItem(blueberryOrangeStrawberryDonut );

        blueberryOrangeChocolateDonut = new Donut(Donut.Icing.BLUEBERRY, Donut.Sprinkle.ORANGE, Donut.Fill.CHOCOLATE);
        RegisterHelper.registerItem(blueberryOrangeChocolateDonut );

        blueberryOrangeVanillaDonut = new Donut(Donut.Icing.BLUEBERRY, Donut.Sprinkle.ORANGE, Donut.Fill.VANILLA);
        RegisterHelper.registerItem(blueberryOrangeVanillaDonut );

        blueberryOrangeCookieDoughDonut = new Donut(Donut.Icing.BLUEBERRY, Donut.Sprinkle.ORANGE, Donut.Fill.COOKIEDOUGH);
        RegisterHelper.registerItem(blueberryOrangeCookieDoughDonut );

        blueberryOrangeBrownieBatterDonut = new Donut(Donut.Icing.BLUEBERRY, Donut.Sprinkle.ORANGE, Donut.Fill.BROWNIEBATTER);
        RegisterHelper.registerItem(blueberryOrangeBrownieBatterDonut );

        blueberryRainbowNoneDonut = new Donut(Donut.Icing.BLUEBERRY, Donut.Sprinkle.RAINBOW, Donut.Fill.NONE);
        RegisterHelper.registerItem(blueberryRainbowNoneDonut );

        blueberryRainbowStrawberryDonut = new Donut(Donut.Icing.BLUEBERRY, Donut.Sprinkle.RAINBOW, Donut.Fill.STRAWBERRY);
        RegisterHelper.registerItem(blueberryRainbowStrawberryDonut );

        blueberryRainbowChocolateDonut = new Donut(Donut.Icing.BLUEBERRY, Donut.Sprinkle.RAINBOW, Donut.Fill.CHOCOLATE);
        RegisterHelper.registerItem(blueberryRainbowChocolateDonut );

        blueberryRainbowVanillaDonut = new Donut(Donut.Icing.BLUEBERRY, Donut.Sprinkle.RAINBOW, Donut.Fill.VANILLA);
        RegisterHelper.registerItem(blueberryRainbowVanillaDonut );

        blueberryRainbowCookieDoughDonut = new Donut(Donut.Icing.BLUEBERRY, Donut.Sprinkle.RAINBOW, Donut.Fill.COOKIEDOUGH);
        RegisterHelper.registerItem(blueberryRainbowCookieDoughDonut );

        blueberryRainbowBrownieBatterDonut = new Donut(Donut.Icing.BLUEBERRY, Donut.Sprinkle.RAINBOW, Donut.Fill.BROWNIEBATTER);
        RegisterHelper.registerItem(blueberryRainbowBrownieBatterDonut );

        vanillaNoneNoneDonut = new Donut(Donut.Icing.VANILLA, Donut.Sprinkle.NONE, Donut.Fill.NONE);
        RegisterHelper.registerItem(vanillaNoneNoneDonut );

        vanillaNoneStrawberryDonut = new Donut(Donut.Icing.VANILLA, Donut.Sprinkle.NONE, Donut.Fill.STRAWBERRY);
        RegisterHelper.registerItem(vanillaNoneStrawberryDonut );

        vanillaNoneChocolateDonut = new Donut(Donut.Icing.VANILLA, Donut.Sprinkle.NONE, Donut.Fill.CHOCOLATE);
        RegisterHelper.registerItem(vanillaNoneChocolateDonut );

        vanillaNoneVanillaDonut = new Donut(Donut.Icing.VANILLA, Donut.Sprinkle.NONE, Donut.Fill.VANILLA);
        RegisterHelper.registerItem(vanillaNoneVanillaDonut );

        vanillaNoneCookieDoughDonut = new Donut(Donut.Icing.VANILLA, Donut.Sprinkle.NONE, Donut.Fill.COOKIEDOUGH);
        RegisterHelper.registerItem(vanillaNoneCookieDoughDonut );

        vanillaNoneBrownieBatterDonut = new Donut(Donut.Icing.VANILLA, Donut.Sprinkle.NONE, Donut.Fill.BROWNIEBATTER);
        RegisterHelper.registerItem(vanillaNoneBrownieBatterDonut );

        vanillaGreenNoneDonut = new Donut(Donut.Icing.VANILLA, Donut.Sprinkle.GREEN, Donut.Fill.NONE);
        RegisterHelper.registerItem(vanillaGreenNoneDonut );

        vanillaGreenStrawberryDonut = new Donut(Donut.Icing.VANILLA, Donut.Sprinkle.GREEN, Donut.Fill.STRAWBERRY);
        RegisterHelper.registerItem(vanillaGreenStrawberryDonut );

        vanillaGreenChocolateDonut = new Donut(Donut.Icing.VANILLA, Donut.Sprinkle.GREEN, Donut.Fill.CHOCOLATE);
        RegisterHelper.registerItem(vanillaGreenChocolateDonut );

        vanillaGreenVanillaDonut = new Donut(Donut.Icing.VANILLA, Donut.Sprinkle.GREEN, Donut.Fill.VANILLA);
        RegisterHelper.registerItem(vanillaGreenVanillaDonut );

        vanillaGreenCookieDoughDonut = new Donut(Donut.Icing.VANILLA, Donut.Sprinkle.GREEN, Donut.Fill.COOKIEDOUGH);
        RegisterHelper.registerItem(vanillaGreenCookieDoughDonut );

        vanillaGreenBrownieBatterDonut = new Donut(Donut.Icing.VANILLA, Donut.Sprinkle.GREEN, Donut.Fill.BROWNIEBATTER);
        RegisterHelper.registerItem(vanillaGreenBrownieBatterDonut );

        vanillaBlueNoneDonut = new Donut(Donut.Icing.VANILLA, Donut.Sprinkle.BLUE, Donut.Fill.NONE);
        RegisterHelper.registerItem(vanillaBlueNoneDonut );

        vanillaBlueStrawberryDonut = new Donut(Donut.Icing.VANILLA, Donut.Sprinkle.BLUE, Donut.Fill.STRAWBERRY);
        RegisterHelper.registerItem(vanillaBlueStrawberryDonut );

        vanillaBlueChocolateDonut = new Donut(Donut.Icing.VANILLA, Donut.Sprinkle.BLUE, Donut.Fill.CHOCOLATE);
        RegisterHelper.registerItem(vanillaBlueChocolateDonut );

        vanillaBlueVanillaDonut = new Donut(Donut.Icing.VANILLA, Donut.Sprinkle.BLUE, Donut.Fill.VANILLA);
        RegisterHelper.registerItem(vanillaBlueVanillaDonut );

        vanillaBlueCookieDoughDonut = new Donut(Donut.Icing.VANILLA, Donut.Sprinkle.BLUE, Donut.Fill.COOKIEDOUGH);
        RegisterHelper.registerItem(vanillaBlueCookieDoughDonut );

        vanillaBlueBrownieBatterDonut = new Donut(Donut.Icing.VANILLA, Donut.Sprinkle.BLUE, Donut.Fill.BROWNIEBATTER);
        RegisterHelper.registerItem(vanillaBlueBrownieBatterDonut );

        vanillaRedNoneDonut = new Donut(Donut.Icing.VANILLA, Donut.Sprinkle.RED, Donut.Fill.NONE);
        RegisterHelper.registerItem(vanillaRedNoneDonut );

        vanillaRedStrawberryDonut = new Donut(Donut.Icing.VANILLA, Donut.Sprinkle.RED, Donut.Fill.STRAWBERRY);
        RegisterHelper.registerItem(vanillaRedStrawberryDonut );

        vanillaRedChocolateDonut = new Donut(Donut.Icing.VANILLA, Donut.Sprinkle.RED, Donut.Fill.CHOCOLATE);
        RegisterHelper.registerItem(vanillaRedChocolateDonut );

        vanillaRedVanillaDonut = new Donut(Donut.Icing.VANILLA, Donut.Sprinkle.RED, Donut.Fill.VANILLA);
        RegisterHelper.registerItem(vanillaRedVanillaDonut );

        vanillaRedCookieDoughDonut = new Donut(Donut.Icing.VANILLA, Donut.Sprinkle.RED, Donut.Fill.COOKIEDOUGH);
        RegisterHelper.registerItem(vanillaRedCookieDoughDonut );

        vanillaRedBrownieBatterDonut = new Donut(Donut.Icing.VANILLA, Donut.Sprinkle.RED, Donut.Fill.BROWNIEBATTER);
        RegisterHelper.registerItem(vanillaRedBrownieBatterDonut );

        vanillaYellowNoneDonut = new Donut(Donut.Icing.VANILLA, Donut.Sprinkle.YELLOW, Donut.Fill.NONE);
        RegisterHelper.registerItem(vanillaYellowNoneDonut );

        vanillaYellowStrawberryDonut = new Donut(Donut.Icing.VANILLA, Donut.Sprinkle.YELLOW, Donut.Fill.STRAWBERRY);
        RegisterHelper.registerItem(vanillaYellowStrawberryDonut );

        vanillaYellowChocolateDonut = new Donut(Donut.Icing.VANILLA, Donut.Sprinkle.YELLOW, Donut.Fill.CHOCOLATE);
        RegisterHelper.registerItem(vanillaYellowChocolateDonut );

        vanillaYellowVanillaDonut = new Donut(Donut.Icing.VANILLA, Donut.Sprinkle.YELLOW, Donut.Fill.VANILLA);
        RegisterHelper.registerItem(vanillaYellowVanillaDonut );

        vanillaYellowCookieDoughDonut = new Donut(Donut.Icing.VANILLA, Donut.Sprinkle.YELLOW, Donut.Fill.COOKIEDOUGH);
        RegisterHelper.registerItem(vanillaYellowCookieDoughDonut );

        vanillaYellowBrownieBatterDonut = new Donut(Donut.Icing.VANILLA, Donut.Sprinkle.YELLOW, Donut.Fill.BROWNIEBATTER);
        RegisterHelper.registerItem(vanillaYellowBrownieBatterDonut );

        vanillaOrangeNoneDonut = new Donut(Donut.Icing.VANILLA, Donut.Sprinkle.ORANGE, Donut.Fill.NONE);
        RegisterHelper.registerItem(vanillaOrangeNoneDonut );

        vanillaOrangeStrawberryDonut = new Donut(Donut.Icing.VANILLA, Donut.Sprinkle.ORANGE, Donut.Fill.STRAWBERRY);
        RegisterHelper.registerItem(vanillaOrangeStrawberryDonut );

        vanillaOrangeChocolateDonut = new Donut(Donut.Icing.VANILLA, Donut.Sprinkle.ORANGE, Donut.Fill.CHOCOLATE);
        RegisterHelper.registerItem(vanillaOrangeChocolateDonut );

        vanillaOrangeVanillaDonut = new Donut(Donut.Icing.VANILLA, Donut.Sprinkle.ORANGE, Donut.Fill.VANILLA);
        RegisterHelper.registerItem(vanillaOrangeVanillaDonut );

        vanillaOrangeCookieDoughDonut = new Donut(Donut.Icing.VANILLA, Donut.Sprinkle.ORANGE, Donut.Fill.COOKIEDOUGH);
        RegisterHelper.registerItem(vanillaOrangeCookieDoughDonut );

        vanillaOrangeBrownieBatterDonut = new Donut(Donut.Icing.VANILLA, Donut.Sprinkle.ORANGE, Donut.Fill.BROWNIEBATTER);
        RegisterHelper.registerItem(vanillaOrangeBrownieBatterDonut );

        vanillaRainbowNoneDonut = new Donut(Donut.Icing.VANILLA, Donut.Sprinkle.RAINBOW, Donut.Fill.NONE);
        RegisterHelper.registerItem(vanillaRainbowNoneDonut );

        vanillaRainbowStrawberryDonut = new Donut(Donut.Icing.VANILLA, Donut.Sprinkle.RAINBOW, Donut.Fill.STRAWBERRY);
        RegisterHelper.registerItem(vanillaRainbowStrawberryDonut );

        vanillaRainbowChocolateDonut = new Donut(Donut.Icing.VANILLA, Donut.Sprinkle.RAINBOW, Donut.Fill.CHOCOLATE);
        RegisterHelper.registerItem(vanillaRainbowChocolateDonut );

        vanillaRainbowVanillaDonut = new Donut(Donut.Icing.VANILLA, Donut.Sprinkle.RAINBOW, Donut.Fill.VANILLA);
        RegisterHelper.registerItem(vanillaRainbowVanillaDonut );

        vanillaRainbowCookieDoughDonut = new Donut(Donut.Icing.VANILLA, Donut.Sprinkle.RAINBOW, Donut.Fill.COOKIEDOUGH);
        RegisterHelper.registerItem(vanillaRainbowCookieDoughDonut );

        vanillaRainbowBrownieBatterDonut = new Donut(Donut.Icing.VANILLA, Donut.Sprinkle.RAINBOW, Donut.Fill.BROWNIEBATTER);
        RegisterHelper.registerItem(vanillaRainbowBrownieBatterDonut );

        /*
        * end - Auto generated by DonutCombos.py
        */
    }
}
